### ISSUE TITLE
Node test does not detect statefulsets when analyzing taints

### ISSUE THREAD

**Issue by dankirkpatrick** [derailed/popeye#1]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
I have GPU nodes with a taint on them.  On those nodes, I do not have any deployments, but I do have a statefulset that tolerates the taint.  Popeye reports, "Found taint `nvidia.com/gpu but no pod can tolerate."  It appears that Popeye only analyzed deployments, not pods, and definitely not statefulsets.  

Also a couple of English grammar bits.  The open quote is not closed properly in your error message.  It should read:

     Found taint `nvidia.com/gpu' but no pod can tolerate.

not: (notice the missing end quote)

     Found taint `nvidia.com/gpu but no pod can tolerate.

Also, it's a bit clunky wording.  "that" would be a better word choice than "but":

     Found taint `nvidia.com/gpu' that no pod can tolerate.

**To Reproduce**
1. Deploy a node pool with taints.
2. Deploy a statefulset to the node pool that tolerates the taint.
3. Run popeye.  Note that it reports the nodes have no pods that can tolerate the taint.

**Expected behavior**
It should analyze pods, not deployments.  Pods can come from jobs, daemonsets, and statefulesets, as well as deployments.

**Versions (please complete the following information):**
 - OS: [OSX]
 - Popeye [0.1.0]
 - K8s [1.12.6]

**Comment by derailed** [comment]
@dankirkpatrick Thank you for this very first report! 

Can you tell me a bit more about how you've started popeye and which namespace are the sts running in ie are we dealing with multiple namespaces or is there a single namespace at play here. Actually Popeye only looks at pods in your cluster, thus I am thinking some pods ie the one defining the tolerations are somehow not getting included.

**Comment by dankirkpatrick** [comment]
I ran Popeye by saying "popeye --cluster <cluster-name>".   Maybe that's my problem?  It only looks in the current namespace, or maybe "default"?

The tainted nodes are GPU nodes, so the only pods running on the node are the infrastructure pods (mostly in kube-system, but we run a few infrastructure things, like Falco, in different namespaces).  The pods with the tolerations are running in a namespace called "kinetica"--it's a stateful set with 3 pods.  Each pod consumes 100% of the GPU resources, so each node has only one non-infrastructure pod on it.

**Comment by derailed** [comment]
@dankirkpatrick Thanks for posting back and your kind words!

Think I might have found the issue. Can you try updating Popeye to the latest and lmk if it still happening?
