### ISSUE TITLE
List with Popeye Codes

### ISSUE THREAD

**Issue by mstoetzer** [derailed/popeye#110]
Not really a feature, but referencing an older issue, where I asked for a list of codes that Popeye displays.

[Issue #95 ](https://github.com/derailed/popeye/issues/95)

I'm not sure where to put this list, so I didn't create a Pull request for this.

I parsed that codes file and created a Markdown table with it (excerpt):

# List of Popeye Codes

### Container

| Code | Message | Severity | Info / Reference |
| --- | --- | --- | --- |
| 100 | Untagged docker image in use | 3 |  |
| 101 | Image tagged "latest" in use | 2 |  |
| 102 | No probes defined | 2 |  |
| 103 | No liveness probe | 2 |  |
| 104 | No readiness probe | 2 |  |
| 105 | "%s probe uses a port#, prefer a named port" | 1 |  |
| 106 | No resources requests/limits defined | 2 |  |
| 107 | No resource limits defined | 2 |  |
| 108 | "Unnamed port %d" | 1 |  |
| 109 | CPU Current/Request (%s/%s) reached user %d%% threshold (%d%%) | 2 |  |
| 110 | Memory Current/Request (%s/%s) reached user %d%% threshold (%d%%) | 2 |  |
| 111 | CPU Current/Limit (%s/%s) reached user %d%% threshold (%d%%) | 3 |  |
| 112 | Memory Current/Limit (%s/%s) reached user %d%% threshold (%d%%) | 3 |  |

@derailed What do you think about this? Do you have any ideas to format it in a better way?

**Comment by mstoetzer** [comment]
We could add a folder like "docs" to the repo.

**Comment by derailed** [comment]
@mstoetzer I think that would be a great addition to the docs. Thank you for your help on this!
