### ISSUE TITLE
Popeye excludes appear to ignore codes list, ignoring whole match instead

### ISSUE THREAD

**Issue by cjbehm** [derailed/popeye#111]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
Using v0.8.6 (and also with v0.8.0; separate bug report incoming re: docker hub)

The list of codes defined for an exclude appear to be ignored, instead popeye ignores the resource entirely if it matches.

Used the information from #96 to define excludes for expected conditions.

**To Reproduce**
1. Have a totally default metrics-server deploy (just for a test, any pod should work though)
2. Run `popeye -n kube-system -s po`
3. Note that metrics-server shows up in the list with a variety of code matches (like no probe defined)
4. Define a spinach.yaml to exclude 102 (readiness probe) from any pod matching "metrics"
```
popeye:
  excludes:
    v1/pods:
      - name: rx:metrics
        codes:
          - 102
```
5. Run `popeye -f spinach.yaml -n kube-system -s po`
6. Note that metrics-server is entirely excluded, not just the intended code 102

**Expected behavior**
Only code 102 should be ignored

**Screenshots**

**Versions (please complete the following information):**
 - Docker image: derailed/popeye:v0.8.6
 - popeye: v0.8.0 (from listed image) and v0.8.6 (manually)
 - k8s: 1.16.8

**Comment by derailed** [comment]
@cjbehm Thank you for this issue! Fixed v0.8.7
