### ISSUE TITLE
Docker hub v0.8.6 appears to contain version 0.8.0 instead

### ISSUE THREAD

**Issue by cjbehm** [derailed/popeye#112]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
The version reported by popeye from Docker Hub is v0.8.0

**To Reproduce**
1. `docker run --rm derailed/popeye:v0.8.6 version`
```
 ___     ___ _____   _____                       K          .-'-.
| _ \___| _ \ __\ \ / / __|                       8     __|      `\
|  _/ _ \  _/ _| \ V /| _|                         s   `-,-`--._   `\
|_| \___/_| |___| |_| |___|                       []  .->'  a     `|-'
  Biffs`em and Buffs`em!                            `=/ (__/_       /
                                                      \_,    `    _)
                                                         `----;  |
Version:   v0.8.0
Commit:    dev
Date:      n/a
Logs:      /tmp/popeye.log
```

**Expected behavior**
Version tag and version output to match.

Downloading the binary of v0.8.6 directly reports the correct version, but the Dockerfile is setting `ENV VERSION=v0.8.0 GO111MODULE=on PACKAGE=github.com/derailed/popeye` in the 0.8.6 tag, which is probably the reason for the mismatch.

**Comment by derailed** [comment]
@cjbehm Thank you for this issue. Great catch! Fixed v0.8.7
