### ISSUE TITLE
popeye doesn´t respect excludes specified in spinach.yaml

### ISSUE THREAD

**Issue by svenmeinking** [derailed/popeye#113]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
We want to exclude some third party resources, which errors we cannot fix. 

**To Reproduce**
1. Run 'popeye -c -f spinach.yaml -l error'
2. See list of errors
PODS (76 SCANNED)                                                            💥 9 😱 0 🔊 0 ✅ 67 88٪
┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅
  · magnolia/cms-magnolia-backup-1234-asfd..................................................💥
    🐳 trigger-upload
      💥 [POP-100] Untagged docker image in use.

3. insert this into spinach.yaml
  # Excludes define rules to exampt resources from sanitization
  excludes:
  [...]
    v1/pod:
      - name: rx:kube
      - name: magnolia/trigger-upload
      - name: magnolia/cms-magnolia-backup-[a-z0-9-]+
4. Run 'popeye -c -f spinach.yaml -l error'
still there.

**Expected behavior**
all pods regarding magnolia, trigger-upload or cms-magnolia-backup not listed at all

**Versions (please complete the following information):**
 - OS: Amazon Linux
 - Popeye 0.8.6
 - K8s 1.16.0

**Additional context**
How to make these excludes work?

**Comment by michaelpporter** [comment]
I too am seeing issues. I am using the example for EKS which looks exactly like the report when I do not include the spinach.yaml

**Comment by derailed** [comment]
@svenmeinking @michaelpporter Thank you both for reporting this! This is on me as I've missed updating the docs during a code update. My Bad! The problem here is the excludes are now using Group/Version/Resource aka GVR which should be a pluralize version of the resource. ie v1/pods in this case. Sorry about the confusion as this is on me!
