### ISSUE TITLE
Extend excludes to allow excluding specific containers of a pod

### ISSUE THREAD

**Issue by djablonski-moia** [derailed/popeye#120]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**

When trying to create a `spinach.yaml` to make Popeye just report unknown and not accepted issues,
I came across the problem of `istio-proxy`sidecar containers, which has no liveness probe by default,
but this is fine for me. Since the container is injected into every pod, every pod gets reported with its
`istio-proxy` container ☹️ 

**Describe the solution you'd like**

It would be perfect if the existing `excludes` syntax could be extended to support specific containers,
e.g. like this:
```
excludes:
  v1/pods:
    - name: rx:.*/.*:istio-proxy
      codes:
      - 103
```
(I have no real preference on the delimiter, but thought the `subresource` delimiter might be okayish, although not technically correct)

**Describe alternatives you've considered**

No alternatives considered (at least no feasible ones came to my mind 😉)

**Additional context**

None

**Comment by derailed** [comment]
@djablonski-moia Thank you for this report! Please check out the v0.8.9 rel notes. Was not keen on using :container syntax so I've decided to add a new exclude tag for containers instead. Please lmk is that works for you?? Tx!!

**Comment by djablonski-moia** [comment]
I'll c heck it out immediately 😄

**Comment by djablonski-moia** [comment]
Not 100% what I had in mind (not skipping scanning altogether but just specific sanitizers), but close enough to be very useful! Thanks for the ultra fast implementation 😃  🥇
