### ISSUE TITLE
Wrong Docker image url in READ.md

### ISSUE THREAD

**Issue by woshizhuyumi** [derailed/popeye#126]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
On popeye README.md page, one Docker image URL is wrong.
I'm new to Popeye and try to run it for the first time, and this small issue confused me for a little while.

**To Reproduce**
1. Go to https://github.com/derailed/popeye#run-public-docker-image-locally
2. There should be a `/` behind `quay.io` but it's missing.

**Expected behavior**
The line should be: 
$ docker run --rm -it -v $HOME/.kube:/root/.kube -v /tmp:/tmp quay.io/derailed/popeye:latest --context foo -n bar --save

**Screenshots**
![image](https://user-images.githubusercontent.com/9000985/92990964-70ee6e80-f534-11ea-8ba3-0b27cde25c38.png)

**Comment by derailed** [comment]
@woshizhuyumi Thank you for reporting this! Docs updated.
