### ISSUE TITLE
Add check for Service with a single endpoint

### ISSUE THREAD

**Issue by marians** [derailed/popeye#138]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
No. The feature request is about adding a check for something that is currently not covered.

**Describe the solution you'd like**

Services backed by only a single endpoint can fail once the endpoitn goes down, e. g. due to a failure of the node running the endpoint pod. Services should ideally be backed by more than one endpoint for high availability.

popeye should inform/warn about services with only a single endpoint.

**Describe alternatives you've considered**
None

**Additional context**

PR: https://github.com/derailed/popeye/pull/135

**Comment by blairham** [comment]
@derailed @marians, can you provide some documentation around this as I don't believe this is the case. I've looked around and have been unsuccessful in finding any recommendation and would like to educate myself more on this as I seem to have been hitting this but cannot resolve it.

**Comment by marians** [comment]
It's easy to explain: If a service has only one pod as a backend, any disruption affecting this single pod (e. g. an update) will take the service offline. The general idea in the Kubernetes world is to avoid these single points of failure and make the application resilient. In this case, a `ReplicaSet` controlling the pod which is backing the service should ensure more than one replica. The service will only route traffic to the backend pods which are ready. This is useful both for performance (load balancing) and for robustness.

As for upstream docs, I found this: https://kubernetes.io/docs/tutorials/kubernetes-basics/scale/scale-intro/

**Comment by marians** [comment]
@blairham Let me know if I missed the point of the question and explained something super obvious.

**Comment by blairham** [comment]
@marians, ok, so as I understand what you are saying, you're not actually talking about the endpoints themselves but replication or more than 1 pod. I think the wording needs to be changed to reflect this as Kubernetes has endpoints and is a misleading message. In addition, the severity should be lowered as there are many situations where a single pod is ok. 

I'll open a couple of bugs around these for further discussion; thank you for clarifying your intent.

**Comment by marians** [comment]
The terminology might be ambigious. When doing `kubectl describe svc` the term "endpoint" is used to describe the IP/port combinations in the pods which the service connects to.

**Comment by blairham** [comment]
Correct, as the in the glossary, there's indeed no entry for endpoint, it is a well-defined Kubernetes network concept or abstraction. Since it's of secondary nature, you'd usually not directly manipulate it. There's a core resource Endpoint defined and it's also supported on the command line:

```
$ kubectl get ep
NAME         ENDPOINTS            AGE
kubernetes   192.168.64.13:8443   10d
```
And there you see what it effectively is: an IP address and a port. Usually, you'd let a service manage endpoints (one EP per pod the service routes traffic to) but you can also manually manage them if you have a use case that requires it.

This is what was tripping me up, as you were more interested in the number of pods that contained an endpoint.

**Comment by kevin-lindsay-1** [comment]
I agree that the wording of this warning is unintuitive.

**Comment by sticksen** [comment]
I also didn´t get it at first glance that it can be (most often) solved by adding a second replica.
But also to understand it deeper: wouldn´t k8s reschedule the Pod to a different Node, if the underlying Node fails? Is this warning mostly about HA?
