### ISSUE TITLE
Emoji don't always render: please prefer ASCII or limited Unicode.

### ISSUE THREAD

**Issue by pnathan** [derailed/popeye#14]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
What is the emoji? I just see boxes on my terminal. 

**To Reproduce**

Run the tool on Konsole on Linux

**Expected behavior**
Colorized output *or* non-emoji textual output.

**Screenshots**
![image](https://user-images.githubusercontent.com/761056/55764501-abd7a300-5a20-11e9-8a26-2936704a7161.png)

**Versions (please complete the following information):**
 - OS: Linux, Terminal is Konsole on KDE5
 - Popeye 0.1.4
 - K8s: 1.9.6 for *this cluster*

**Additional context**

This is both a cross-platform and an accessibility issue.

**Comment by pnathan** [comment]
Note - I can submit a PR that looks like

![image](https://user-images.githubusercontent.com/761056/55765805-44245680-5a26-11e9-9a01-bd4f109247de.png)

but I suspect that an "emoji-on/-off" flag would be preferred, yes?

**Comment by derailed** [comment]
@pnathan Thank you for this report! I think scanning the user env vs flags might be a better approach to this. Thus tuning the sanitizer down based on the capabilities of the terminal.

**Comment by pnathan** [comment]
@derailed spent a few minutes rummaging about. It looks like this is partially dependent on rendering engine (terminal emulator) _and_ font, which is annoying.  One trick suggested here is - https://stackoverflow.com/a/44445547 - I copypasted from my terminal to run it - 

`echo -n  🔊 | wc -m `

but that simply returns one, just like `echo -n w | wc -m`  does. So that seems to be a wash (-m returns number of characters: an emoji should be one character, regardless of byte length, just like, e.g., a kanji. So that seems to be a poor mechanism of assessing anyway).

It might be that switching on the environment variable `TERM` is the proper thing to do:

emacs-shell gives `dumb` and my Konsole terminal gives `xterm-256color`. 

This is probably a minefield of "switch case", but plausibly it might work. 

Contemplating, it might be that the proper thing to do would look a lot like `ls --color`

```
      --color[=WHEN]         colorize the output; WHEN can be 'always' (default
                               if omitted), 'auto', or 'never'; more info below
```

where `auto` tries to figure itself out, `never`, and `always` can be specified.

**Comment by derailed** [comment]
@pnathan Thank you so much for your investigation and report! I'll take a look at this on the next drop and see if we can figure out a way to compliment the various terminals in the report.

**Comment by derailed** [comment]
@pnathan I've added a flag in 0.2.0 -j or --jurassic based on some of your recommendations, hopefully that will help some... Thank you!
