### ISSUE TITLE
Output format 'prometheus' should be useable with --save and without push gateway

### ISSUE THREAD

**Issue by marians** [derailed/popeye#141]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**

It is currently not possible (or not easy) to take a look at the prometheus metrics generated, without having a pushgateway running.

**Describe the solution you'd like**

I'd like to run `popeye --save --out prometheus` and get a text file as an output, containing all the data that would get send to a push gateway.

**Describe alternatives you've considered**

Provide a complete example for the prometheus output in documentation and keep that up-to-date.

**Additional context**

Currently, the `--pushgateway-address` flag is required when setting the `prometheus` output type.

When setting an invalid pushgateway address, there is an output file generated, but it is empty. The following error output  is shown:

```nohighlight
$ popeye --save --out prometheus --pushgateway-address http://localhost:909
/var/folders/mr/0glbgq6973x4dw2yhnz9qvn40000gn/T/popeye/sanitizer_my-context_1604407267151450000.txt
 ___     ___ _____   _____                       D          .-'-.
| _ \___| _ \ __\ \ / / __|                       O     __| K    `\
|  _/ _ \  _/ _| \ V /| _|                         H   `-,-`--._   `\
|_| \___/_| |___| |_| |___|                       []  .->'  X     `|-'
  Biffs`em and Buffs`em!                            `=/ (__/_       /
                                                      \_,    `    _)
                                                         `----;  |


Boom! 💥 Post "http://localhost:909/metrics/job/popeye": dial tcp [::1]:909: connect: connection refused
```

**Comment by woshizhuyumi** [comment]
Hi @marians , just wondering how the entire Popeye-Prometheus process works?

Given:
I have a cluster running on Azure.

I want to:
send Popeye result to Prometheus Pushgateway

What I have tried:
Run Popeye inside of the cluster, as a cronjob. Every time a job is created, I can get the result by output the pod log.(End the pod ends up in Error STATE, after putting the result in its log.......)
But I have actually no idea(or anywhere I can see in Doc) how to use `-o prometheus` to save the result in Prometheus format! 

I cannot really install Popeye cli on the cluster machine sadly....
Wondering does saving the result in Prometheus format only available when using Popeye cli, **NOT** available for running as a Cronjob?

**Comment by marians** [comment]
@zhuyumi Sorry, can't help here, since I'm not running popeye in the cluster.
