### ISSUE TITLE
Additional flags: "report only", "score threshold" and "exit code"

### ISSUE THREAD

**Issue by bygui86** [derailed/popeye#151]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
Running Popeye in my cluster as Job, if the score is not high enough (I suppose > 90), the whole run will fail because the exit code is 1.

**Describe the solution you'd like**
Locally and inside a CI/CD pipeline, it's good to have the popeye command failing in case of score not high enough, but as a Kubernetes Job in my opinion it does not always matter. Considering also that the score threshold is not configurable.
I suggest to add a couple of flags:
- a (boolean) flag to set that the run is only to generate a report
  for example `--report-only`
- a (numeric) flag to set the score threshold, under which the command exit with code 1 (or different than 0)
  for example `--min-score-threshold/-t`
- a (numeric) flag to set the exit code no matter the score
  for example `--exit-code/-e`

**Describe alternatives you've considered**
For now I just avoid to run the job again in case of failure, so I'm able to easily export the report and analyze it.

**Comment by derailed** [comment]
@bygui86 PR #150

**Comment by bygui86** [comment]
@derailed thanks a good PR!

What about "a (numeric) flag to set the score threshold, under which the command exit with code 1 (or different than 0)
for example --min-score-threshold/-t" ?

It could be really useful in case of some "temporary compromises" in a CI/CD :)
