### ISSUE TITLE
Feat: Add Support Basic HTTP Auth for Prometheus Output

### ISSUE THREAD

**Issue by bryankaraffa** [derailed/popeye#164]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
Currently Popeye Prometheus output does not support basic HTTP auth for prometheus.  

We would like to regularly test and push the findings to a centralized prometheus environment which will enable us to look at results for multiple clusters in a single pane.  Currently our pushgateway is secured with HTTP Basic Auth

**Describe the solution you'd like**
Add support for Prometheus output to use HTTP Basic auth if provided.. Perhaps new flags like `--pushgateway-basic-auth-user` and `--pushgateway-basic-auth-pass`:
```
popeye \
      --output prometheus \
      --pushgateway-address https://pushgateway.monitoring.foobar.com \
      --pushgateway-basic-auth-user foobar \
      --pushgateway-basic-auth-pass hunter2
```
This appears to be something that already is supported in the prometheus push go module:
https://github.com/prometheus/client_golang/blob/3998a677f90d93348cf4f079f68f7c0e1392cfc5/prometheus/push/push.go#L67-L83

but not used by popeye yet:
https://github.com/derailed/popeye/blob/a80f6aeb06be01e0d5384b836239e09c8eadd4aa/internal/report/prometheus.go#L75

**Comment by derailed** [comment]
@bryankaraffa Let's give that a rinse on v0.9.1
