### ISSUE TITLE
Skip checks at container level

### ISSUE THREAD

**Issue by arvan-pritchard** [derailed/popeye#168]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
spinach configuration allows you to skip all checks for a container or codes for all containers in a pod. I'd like to skip particular codes on specific containers.

e.g. I know my 'fred' pod has a 'jim' container that has to run as root, but would like to check other problems on that container and other containers in the same pod running as root

**Describe the solution you'd like**
Allow specification of a list of codes on a container. Something like

<pre>
popeye:
  excludes:
    v1/pods:
    - name: rx:fred
      containers:
        - name: jim
          codes:
              302
</pre>

**Describe alternatives you've considered**
Could alternatively have a different field e.g. 'containercodes' which is a map of container names to lists of codes, rather than redefining 'containers' to be structured
At present I need to leave codes unsuppressed and postprocess the Popeye output.

**Comment by derailed** [comment]
Fixed v0.25.6
