### ISSUE TITLE
can't run popeye when kubernetes has networking.k8s.io/v1/ingresses

### ISSUE THREAD

**Issue by woodliu** [derailed/popeye#170]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
When i download the released binary file, and run "./popeye", it shows "Boom! No resource meta found for networking.k8s.io/v1/ingresses".
Can I skip the resource?

**To Reproduce**
just run "./popeye"

**Expected behavior**
popeye can run as normal

**Screenshots**

**Versions (please complete the following information):**
![image](https://user-images.githubusercontent.com/9976943/119442876-3263b180-bd5b-11eb-9c0b-dd25cf5300c9.png)

**Additional context**

**Comment by kk-kwok** [comment]
I also encountered the same problem。

kubernetes version: v1.18.4
popeye version: 0.9.2

# popeye --context develop                                                                                                                                                                                                                              
 ___     ___ _____   _____                       D          .-'-.
| _ \___| _ \ __\ \ / / __|                       O     __| K    `\
|  _/ _ \  _/ _| \ V /| _|                         H   `-,-`--._   `\
|_| \___/_| |___| |_| |___|                       []  .->'  X     `|-'
  Biffs`em and Buffs`em!                            `=/ (__/_       /
                                                      \_,    `    _)
                                                         `----;  |


Boom! No resource meta found for networking.k8s.io/v1/ingresse

**Comment by kk-kwok** [comment]
I cloned the git code to my computer, and modified the following two files, changed "networking.k8s.io/v1/ingresses" to "networking.k8s.io/v1beta1/ingresses" and then executed "go build" to build a new one "popeye", this new popeye can work normally now.

pkg/popeye.go
internal/dag/ing.go

**Comment by kk-kwok** [comment]
> <img alt="" width="100" height="auto" src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png">
> 
> 
> 
> 
> **Describe the bug**
> When i download the released binary file, and run "./popeye", it shows "Boom! No resource meta found for networking.k8s.io/v1/ingresses".
> Can I skip the resource?
> 
> **To Reproduce**
> just run "./popeye"
> 
> **Expected behavior**
> popeye can run as normal
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Versions (please complete the following information):**
> ![image](https://user-images.githubusercontent.com/9976943/119442876-3263b180-bd5b-11eb-9c0b-dd25cf5300c9.png)
> 
> **Additional context**
> Add any other context about the problem here.

I cloned the git code to my computer, and modified the following two files, changed "networking.k8s.io/v1/ingresses" to "networking.k8s.io/v1beta1/ingresses" and then executed "go build" to build a new one "popeye", this new popeye can work normally now.

pkg/popeye.go
internal/dag/ing.go

**Comment by stephenpope** [comment]
I have the same issue with running against any `v1.18` cluster (and I assume any version before that). This issue should probably be renamed as related to Popeye not working with K8S v1.18.

**Comment by kk-kwok** [comment]
> I have the same issue with running against any `v1.18` cluster (and I assume any version before that). This issue should probably be renamed as related to Popeye not working with K8S v1.18.

clone code and modifie the following two files, change "networking.k8s.io/v1/ingresses" to "networking.k8s.io/v1beta1/ingresses" and then execute. "go build" to build a new one "popeye", this new popeye can work normally now.

pkg/popeye.go
internal/dag/ing.go

**Comment by woodliu** [comment]
> > I have the same issue with running against any `v1.18` cluster (and I assume any version before that). This issue should probably be renamed as related to Popeye not working with K8S v1.18.
> 
> clone code and modifie the following two files, change "networking.k8s.io/v1/ingresses" to "networking.k8s.io/v1beta1/ingresses" and then execute. "go build" to build a new one "popeye", this new popeye can work normally now.
> 
> pkg/popeye.go
> internal/dag/ing.go

Yeah，popeye do not support the kubernetes which the "Ingress" resource version under "v1"

**Comment by shelltea** [comment]
same problem

**Comment by TalZiv** [comment]
I have the same problem the weird thing is that popeye works in k9s. Hope this get fixed soon.

**Comment by previousdeveloper** [comment]
same problem with Kubernetes v.1.16.11

**Comment by peddyspg** [comment]
Will be there a fix?
I installed popeye via "brew" on mac os x. I would prefer to use brew updates.

My settings are:
`
popeye version
Version:   0.9.2
Commit:    83d93417b627afe24c642f110b72651e8a59f49

kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.17-gke.1901", GitCommit:"b5bc948aea9982cd8b1e89df8d50e30ffabdd368", GitTreeState:"clean", BuildDate:"2021-05-27T19:56:12Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

`

**Comment by SamuAlfageme** [comment]
Still getting the same outcome with the latest release and a cluster v1.18.2:

```
popeye version
 ___     ___ _____   _____                       K          .-'-.
| _ \___| _ \ __\ \ / / __|                       8     __|      `\
|  _/ _ \  _/ _| \ V /| _|                         s   `-,-`--._   `\
|_| \___/_| |___| |_| |___|                       []  .->'  a     `|-'
  Biffs`em and Buffs`em!                            `=/ (__/_       /
                                                      \_,    `    _)
                                                         `----;  |
Version:   0.9.3
Commit:    2cea93981a67ad138aa81efe2ad8c1889523626b
Date:      2021-06-22T13:19:25Z
Logs:      /var/folders/j6/fjghmgt97jnc6yzrr6b35_l40000gn/T/popeye.log

popeye
 ___     ___ _____   _____                       D          .-'-.
| _ \___| _ \ __\ \ / / __|                       O     __| K    `\
|  _/ _ \  _/ _| \ V /| _|                         H   `-,-`--._   `\
|_| \___/_| |___| |_| |___|                       []  .->'  X     `|-'
  Biffs`em and Buffs`em!                            `=/ (__/_       /
                                                      \_,    `    _)
                                                         `----;  |


Boom! No resource meta found for networking.k8s.io/v1/ingresses

kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```

Q: Does the version difference between `kubectl` and the cluster's could affect the version detected by `popeye` somehow?

**Comment by dignajar** [comment]
the same error in version 0.9.3.

```
kubectl version

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.18", GitCommit:"6f6ce59dc8fefde25a3ba0ef0047f4ec6662ef24", GitTreeState:"clean", BuildDate:"2021-04-15T03:23:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
