### ISSUE TITLE
Can't run Popeye

### ISSUE THREAD

**Issue by Thanzex** [derailed/popeye#171]
**Description**
Running popeye both on my local machine and on a server that runs k8s popeye fails immediately with
`Boom! 💥 unable to retrieve the complete list of server APIs: server.com/v1alpha1: the server is currently unable to handle the request`.
 
The cluster works just fine and the API server is operational, `kubectl` works on both machines
I'm running k3s, but there shouldn't be any problems with it as I did use this tool on previous versions.

**Expected behavior**
Popeye should work.

**Versions**
- Local machine: **Windows**
  - kubectl 1.20.1
- Kubernetes: **v1.20.4+k3s1**
  - kubectl 1.20.4

Is there anything I can provide to you to debug this?

**Comment by DidierHoarau** [comment]
Hi,

I've encountered a similar issue.

The message I get is:
`Boom! 💥 unable to retrieve the complete list of server APIs: compose.docker.com/v1alpha3: the server is currently unable to handle the request, compose.docker.com/v1beta1: the server is currently unable to handle the request, compose.docker.com/v1beta2: the server is currently unable to handle the request, metrics.k8s.io/v1beta1: the server is currently unable to handle the request`

After a bit of search I found this post: https://github.com/helm/helm/issues/6361

It seems that it is linked to some apiservice being down. My assumption is that if you do `kubectl get apiservices`, all services should be available except the one that appear in the error message.

A workaround/suggestion/(solution?) seems to be to fix or delete the one that are not marked as "available". I have not done it yet... investigating if it is safe first.

I hope it helps

**Comment by yelinaung** [comment]
I had the same issue 
```
Boom! 💥 unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server could not find the requested resource, external.metrics.k8s.io/v1beta1: the server could not find the requested resource
```

The solution that worked for me (from the helm issue link above) is 
- deleting all the `apiservices` with AVAILABLE being `False`
- deleting this particular `apiservices` -
```
v1beta1.metrics.k8s.io                    kube-system/metrics-server   True        17s
```
- finding the `metric-server` in the cluster by `k get deployment -A  | grep "metrics"` and restarting it with `k rollout restart deployment -n kube-system metrics-server-v0.3.6` (this is the version I have in my cluster)
- as part of the restart, the metrics-server will re-install the `v1beta1.metrics.k8s.io` api-services.
- waited for a while and after that I am able to get the results from `popeye`

Hope this helps!
