### ISSUE TITLE
Custom handling of client-go/rest warnings

### ISSUE THREAD

**Issue by Goodwine** [derailed/popeye#178]
_Required by my employer: "Not a Contribution."_
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

### Is your feature request related to a problem? Please describe.

When running popeye, `client-go/rest` may output warnings to stderr such as deprecated resources or throttling.

`client-go/rest` has a setting to change this behavior or disable such warnings, and it would be nice if Popeye allowed customizing or setting a warning handler.

### Describe the solution you'd like
Ideally being able to define my own handler

### Describe alternatives you've considered
If defining my own handler is not feasible, it would be cool to at least be able to set a flag that would disable warnings. 

### Additional context
Not currently allowed to share technical solution or provide code samples, however both possible solutions are mentioned and documented here:
https://kubernetes.io/blog/2020/09/03/warnings/#customize-client-handling

**Comment by derailed** [comment]
@Goodwine Thank you for the heads up! Routing warning to the logger now. Let' see if we're happier on v0.9.6...
