### ISSUE TITLE
[CI?] Popeye docker image tag 0.9.6 not available on quay.io

### ISSUE THREAD

**Issue by julien-sugg** [derailed/popeye#190]
Hi,

I started playing with Popeye today and I am having some issue to pull the most recent version of the Docker image (v0.9.6).

<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
It's not really a bug from a business perspective, however there appear to be an issue, probably in CI, that prevents the Docker image from being pushed to the quay.io registry.

e.g. I expected the `docker pull quay.io/derailed/popeye:v0.9.6` to be pullable but it appears that only v0.9.1 is available on quay.io.

**To Reproduce**
1. Run `docker pull quay.io/derailed/popeye:v0.9.6`
2. A pull related error should occur: `manifest for quay.io/derailed/popeye:v0.9.6 not found`

**Expected behavior**
The latest version of popeye to be available on Docker in order to run it as a (Cron)Job within the cluster.

**Screenshots**
Not applicable

**Versions (please complete the following information):**
 - OS: not applicable
 - Popeye: v0.9.6
 - K8s: not applicable

**Additional context**
It appears that the latest tag available on quay.io is v0.9.1

```shell
curl -X GET https://quay.io/v2/derailed/popeye/tags/list | jq
{
  "name": "derailed/popeye",
  "tags": [
    "v0.3.6",
    "v0.3.7",
    "v0.3.8",
    "v0.3.9",
    "v0.3.10",
    "v0.3.11",
    "v0.3.12",
    "v0.3.13",
    "v0.4.0",
    "v0.4.1",
    "v0.4.2",
    "v0.4.3",
    "v0.5.0",
    "v0.6.0",
    "v0.6.1",
    "v0.6.3",
    "v0.6.2",
    "v0.7.0",
    "v0.7.1",
    "v0.8.0",
    "v0.8.1",
    "v0.8.2",
    "v0.8.3",
    "v0.8.4",
    "v0.8.5",
    "v0.8.6",
    "v0.8.7",
    "v0.8.8",
    "v0.8.9",
    "v0.8.10",
    "v0.9.0",
    "v0.9.1",
    "master",
    "latest",
    "POP-186-_186"
  ]
}
```

**Comment by derailed** [comment]
@julien-sugg Great report! Thank you Julien!! Looks like we're getting rev limited ;( Switching out to DockerHub on the next drop.  In the meantime `docker pull derailed/popeye:v0.9.6`...

**Comment by ulfatufo** [comment]
> @julien-sugg Great report! Thank you Julien!! Looks like we're getting rev limited ;( Switching out to DockerHub on the next drop. In the meantime `docker pull derailed/popeye:v0.9.6`...

- [ ] 

- **#[](url)**
