### ISSUE TITLE
Old popeye docker image host in k8s cronjob.yml config

### ISSUE THREAD

**Issue by jolet** [derailed/popeye#192]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
Please reflect latest docker image relocation in k8s/popeye/cronjob.yml config, it still points to quay.io

**To Reproduce**
1. Clone the repo and install popeye as desribed in "Popeye In Your Clusters!" section
=> old quay.io image pulled as "latest"

**Expected behavior**
latest image pulled from docker hub instead of quay.io

**Screenshots**

**Versions (please complete the following information):**
 - OS: Linux
 - Popeye v0.9.7
 - K8s v1.21.1

**Additional context**

**Comment by derailed** [comment]
@jolet Oops! Thank you for the heads up!! Fixed!
