### ISSUE TITLE
Typo in popeye code definitions

### ISSUE THREAD

**Issue by Selin-PDQ** [derailed/popeye#193]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
There's a typo in [this MD file](https://github.com/derailed/popeye/blob/master/docs/codes.md#persistantvolume-persistantvolumeclaim)
`persistantvolumeclaim` should be spelled `persistentvolumeclaim`

**Describe the solution you'd like**
Probably just correct the typo

**Describe alternatives you've considered**
I just saw this one typo. It might be worth identifying other grammatical issues in that doc.

**Additional context**
I'll give the rest of the doc a check for grammatical issues and open a PR with my suggestions. If this PR is too low-level or nitpicky I'm totally okay with not opening a PR to correct it.

**Comment by Selin-PDQ** [comment]
is it okay for me to fork this repo and open a PR that fixes this? I wasn't able to find any contributing guidelines.

**Comment by derailed** [comment]
@Selin-PDQ Ah good catch! sure - PR away!

**Comment by Selin-PDQ** [comment]
Thanks! I've fixed it and opened a PR here:
https://github.com/derailed/popeye/pull/194
