### ISSUE TITLE
How to fix POP-300 : Using “default” ServiceAccount ?

### ISSUE THREAD

**Issue by michelzanini** [derailed/popeye#195]
Hi,

Sorry for this question, if it's not the correct place to ask, etc...

But I have been trying to fix POP-300 ("Using "default" ServiceAccount") but I am not really sure how to do that.
I know I can set a different `serviceAccountName` but I don't have any service account I wish to use.

I am just running a simple Java pod/deployment, what should I do in this case?

If I should do nothing and ignore POP-300 by filtering it out, then I wonder why this is set to severity 2 (warning).

**Comment by derailed** [comment]
@michelzanini Right! as you are finding your application uses the default serviceaccount which is generic and does not accurately represent what your application can or cannot do on your clusters. POP-300 warns you of that situation. So you can either exclude the code in your spinach.yml file if this does not apply or create a serviceaccount representing your application which will allow you to attach RBAC rules for your application. Does this make sense?

**Comment by michelzanini** [comment]
Ok. Most applications won't need RBAC or K8S API access. That means probably going the ignore route would be the best? Or is it worth having a empty service account each app which is not called default?

**Comment by derailed** [comment]
@michelzanini yes I think this make sense as you can then lock down your app with rbac.
