### ISSUE TITLE
[Docs] Description, reasoning, and examples for codes

### ISSUE THREAD

**Issue by kevin-lindsay-1** [derailed/popeye#197]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
I would call it a documentation problem more than anything.

**Describe the solution you'd like**
When I use popeye via `k9s`, I get the `POP-` error/warning codes and their messages, similar to something like `eslint`, however generally the purpose of these codes it to look them up, and from what I've seen the only "documentation" on these codes is simply an index of all the codes.

It would be good to describe the code in greater detail, and preferably include good and bad examples that would trigger such a code, similar to how eslint does in their docs. For example, https://eslint.org/docs/rules/no-shadow.

Maybe including a link in the output code directly to the docs would be a good idea, too.

**Describe alternatives you've considered**
Can't really think of any. In my opinion, `eslint` sets a really good bar for quality documentation regarding error codes like this.

**Comment by ivorodrigues** [comment]
A good sugestion would be something like https://hub.armo.cloud/docs/c-0006
