### ISSUE TITLE
all docker tags are not available on quay.io

### ISSUE THREAD

**Issue by yogeek** [derailed/popeye#199]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
I wanted to deploy the latest popeye release `v0.9.7` and did not found the corresponding docker image. 
It seems that every tag corresponding to popeye releases are not pushed to quay.io. 
The last "non-latest" tag is  `v0.9.1` in  https://quay.io/repository/derailed/popeye?tab=tags
Is it intentional to not have every tags ?

**Comment by derailed** [comment]
@yogeek - I am sorry, that's on me! Missed some refs to quay.io ;( The official Popeye images are on [dockerhub](https://hub.docker.com/r/derailed/popeye)

**Comment by yogeek** [comment]
@derailed ok thank you !
