### ISSUE TITLE
Popeye does not consider "startupProbe" as a valid probe and lists the pods with "No probes defined"

### ISSUE THREAD

**Issue by yashodhanmohan** [derailed/popeye#206]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
For containers that only have a startup probe, popeye only checks for liveness probe and readiness probe. This causes it declare that there are no probes defined even though there are. If the plan is to only check for liveness or readiness probe, the error message should probably change.

**To Reproduce**
1. Scan a cluster with a pod with a container that contains a startupProbe but no liveness or readiness probe

**Expected behavior**
No error message that says "No probes defined". At the least, the error message should say that "No liveness or readiness probe defined"

**Screenshots**
-

**Versions (please complete the following information):**
 - OS: macOS Monterey v12.0.1
 - Popeye v0.9.8
 - K8s v1.21.0

**Comment by Berber31** [comment]
mmm i agree with popeye for that, cause startup probe is only executed until succes threshold is reached (and only then liveness and readiness are exected (https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes)
startup probe is NOT executed along the container lifecycle
so a startup probe is not enouth to check liveness or readiness during execution

**Comment by derailed** [comment]
@yashodhanmohan - @Berber31 is correct. Startup probe is a convenience for slow starting workloads. Readiness/Liveness probes are additional hints to k8s do indicate the "health" of your workload and hence should be a good practice to observe in most cases.

**Comment by yashodhanmohan** [comment]
Ahh that makes sense I guess. Confusion from my side. Cheers!
