### ISSUE TITLE
I cloned the project and solved the Kubernetes 1.23.1 version access problem, but the file size packed locally is five times bigger than the release version, why is that?

### ISSUE THREAD

**Issue by Fcscanf** [derailed/popeye#208]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/27654200/147455110-dd9e0bf2-e500-4d31-aa32-800434db0b15.png)
This is my package size
![image](https://user-images.githubusercontent.com/27654200/147455235-56b72bb9-5db1-4941-a44b-c17f5933944a.png)

**Versions (please complete the following information):**
 - OS: [e.g. OSX]
 - Popeye [e.g. 0.1.0]
 - K8s [e.g. 1.11.0]

**Additional context**

**Comment by derailed** [comment]
@Fcscanf Likely because debug info is included in your binary
