### ISSUE TITLE
POP-403 - PodSecurityPolicy (PSP) k8s v1.21 deprecation - k8s v1.25 deletion - not detected

### ISSUE THREAD

**Issue by Berber31** [derailed/popeye#209]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
POP-403 (PodSecurityPolicy deprecated since k8s v1.21 and deleted in v1.25) is not detected

**To Reproduce**
1. Deploy a PodSecurityPolicy (group policy/v1beta1) on k8s v1.21.11 cluster
2. Scan with (`popeye -s psp`)
3. Read the report
4. No `POP-403 - Deprecated PodSecurityPolicy API group policy/v1beta1` shown

**Expected behavior**
`POP-403 - Deprecated PodSecurityPolicy API group policy/v1beta1` message shown

**Screenshots**
NA

**Versions (please complete the following information):**
 - OS: [e.g. OSX]
 - Popeye [0.9.8]
 - K8s [1.21.11]

**Additional context**
NA

**Comment by derailed** [comment]
Fixed v0.20.0
