### ISSUE TITLE
Installing popeye from snap doesn't work correctly

### ISSUE THREAD

**Issue by accountgit** [derailed/popeye#21]
$ sudo snap install popeye
$ popeye
💥 Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused
Running the same version from binary releases works as expected.

Tested in ubuntu 18.10.

**Comment by derailed** [comment]
@accountgit Thank you for the report! Making a bit of progress with the snap folks but still waiting for an approval on their side. Hopefully soon...

**Comment by derailed** [comment]
@accountgit I think this is finally resolved. Had a long process to get the right perms with the kind folks at SnapCraft. Hopefully all good with v0.3.10 and beyond...
