### ISSUE TITLE
v1 Ingress in K8s v1.22 not found

### ISSUE THREAD

**Issue by MikaelSmith** [derailed/popeye#211]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
```
INGRESSES (1 SCANNED)                                                          💥 1 😱 0 🔊 0 ✅ 0 0٪
┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅
    💥 the server could not find the requested resource.
```

**To Reproduce**
1. Use Docker Desktop (or presumably another Kubernetes v1.22.5 environment)
2. Install a v1 Ingress
3. Run popeye

**Expected behavior**
Ingress resources should be fine. They were ok with popeye 0.9.0 (except it warned that the v1 API was deprecated).

**Screenshots**

**Versions (please complete the following information):**
 - OS: macOS
 - Popeye 0.9.8
 - K8s v1.22.5

**Comment by Berber31** [comment]
when you say `v1 Ingress` you probably mean `networking.k8s.io/v1beta1` ?
cause in experienced the same for `networking.k8s.io/v1beta1` deprecated since k8s v1.19 and deleted in k8s v1.22

**Comment by MikaelSmith** [comment]
No, in this case I've installed a `networking.k8s.io/v1` Ingress.

**Comment by Berber31** [comment]
> No, in this case I've installed a `networking.k8s.io/v1` Ingress.

ho sorry, my bad, you'r right i misunderstood your issue (too exited to expect an opened issue with `networking.k8s.io/v1beta1` )

**Comment by djablonski-moia** [comment]
@derailed I was able to fix this locally by replacing all `netv1b1` usages with `netv1` imports, but I'm afraid this will break backwards compatibility. Can you hint me to a place where you solved something similar? I would try to create a PR then.

**Comment by djablonski-moia** [comment]
For the time being, it works for me with the binary built from the PR above. If anyone wants to give it a try with older versions than 1.22, I'd be happy to some feedback 😉

**Comment by MikaelSmith** [comment]
Fixed my issue. I have a Kubernetes 1.19 environment I'll test as well.

**Comment by MikaelSmith** [comment]
Seems to also work fine in a K3s 1.19 test environment. I have no idea if it will work on anything older than that.
