### ISSUE TITLE
Ingress `networking.k8s.io/v1beta1` deprecated since k8s v1.19 and deleted in k8s v1.22, is not detected ONLY in specific namespace name as `kube-metriques`

### ISSUE THREAD

**Issue by Berber31** [derailed/popeye#212]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
Ingress `networking.k8s.io/v1beta1` deprecated since k8s v1.19 and deleted in k8s v1.22, is not detected when deployed into specific namespace name as `kube-metriques`

**To Reproduce**
1. Apply an Ingress `networking.k8s.io/v1beta1` into `kube-metriques` namespace
2. Scan it ! `popeye - n kube-metriques`
4. No POP-403 detected on Ingress

**Expected behavior**
`POP-403 - Deprecated Ingress API group networking.k8s.io/v1beta1` message in scan report

**Screenshots**
NA

**Versions (please complete the following information):**
 - OS: ubuntu
 - Popeye 0.9.8
 - K8s 1.20 and 1.21

**Additional context**
NA

**Comment by derailed** [comment]
Fixed v0.20.0
