### ISSUE TITLE
Ingress `extensions/v1beta1` deprecated (and deleted in k8s v1.22) is not detected ONLY in kube-metriques namespace

### ISSUE THREAD

**Issue by Berber31** [derailed/popeye#213]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
Ingress `extensions/v1beta1` deprecated (and deleted in k8s v1.22), is not detected when deployed on specific namespace (kube-metriques)

**To Reproduce**
1. Apply an Ingress `extensions/v1beta1` into `kube-metriques` namespace
2. Scan it ! `popeye -n kube-metriques`
4. No POP-403 detected on Ingress API group extensions/v1beta1

**Expected behavior**
`POP-403 - Deprecated Ingress API group extensions/v1beta1` message in scan report

**Screenshots**
NA

**Versions (please complete the following information):**
 - OS: ubuntu
 - Popeye 0.9.8
 - K8s 1.20 and 1.21

**Additional context**
No

**Comment by derailed** [comment]
Fixed v0.20.0
