### ISSUE TITLE
[POP-1100] No pods match service selector - should not be detected for `ExternalName` service type 

### ISSUE THREAD

**Issue by Berber31** [derailed/popeye#214]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
A POP-1100 issue should not be detected for ExternalName service type

**To Reproduce**
1. Deploy an `ExternalName` service type
2. Scan it
3. Issue `[POP-1100] No pods match service selector` is detected 

**Expected behavior**
Issue `[POP-1100] No pods match service selector` should not be detected 

**Screenshots**
NA

**Versions (please complete the following information):**
 - OS: ubuntu
 - Popeye : 0.9.8
 - K8s: 1.20

**Additional context**
NA

**Comment by derailed** [comment]
Fixed v0.20.0
