### ISSUE TITLE
Output as Yaml or JSON?

### ISSUE THREAD

**Issue by ChrisCooney** [derailed/popeye#22]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
I wanted to use this tool as part of a regular set of scans that run against our cluster. We could then output the logs of this scan to an elasticsearch instance and visualise the current (and previous) score of our cluster.

**Describe the solution you'd like**
The kubectl CLI provides a `-o` flag that allows `yaml`, `json`, `wide` etc. Outputting the contents of the report into a parseable format like yaml or json would be perfect.

**Describe alternatives you've considered**
I played around with some sed scripts but it felt a little hacky.

**Additional context**

**Comment by derailed** [comment]
@ChrisCooney  Thank you for your report! I've added json/yaml output and you should be able to run Popeye in cluster too depending on your scenario. Can you give 0.3.3 a try and see if that helped? Tx!!
