### ISSUE TITLE
POP-400 on (nearly) all namespaces?

### ISSUE THREAD

**Issue by howardjones** [derailed/popeye#228]
**Describe the bug**

With an Azure AKS cluster running k8s 1.21.7, using my admin credentials, popeye reports almost all namespaces in the cluster as POP-400 "Used?".

**To Reproduce**
1. Run popeye against cluster

**Expected behavior**
These namespaces all have applications running in them. I expected that to be considered a "reference" for the namespace.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Ubuntu 20.04
 - Popeye 0.10.1
 - K8s 1.21.7

**Additional context**

I just re-ran to confirm, and noticed that if my default namespace is something other than 'default', _that_ namespace doesn't get flagged, but it does if default is 'default'. With default as 'default', _every_ namespace, including 'default' is flagged. My user can see into all these namespaces with, say, `kubectl get pods -n cert-manager`

**Comment by mnpenner** [comment]
*One* of my namespaces has a ✅ but I don't know what makes that one different. They all have stuff running in them.

**Comment by zapman449** [comment]
Several suggestions:

1. POP-400 should not trigger on the `default` service account in a namespace, because it will always exist, whether used or not.
2. POP-400 needs to review cronjob spec for service accounts before claiming "not used"

**Comment by howardjones** [comment]
What I was seeing was the Namespaces themselves. And judging by the lack of any notices for anything in them, popeye is not seeing their content.

**Comment by derailed** [comment]
Fixed v0.20.0
