### ISSUE TITLE
wrong warning: [POP-107] No resource limits defined

### ISSUE THREAD

**Issue by peddyspg** [derailed/popeye#231]
**Describe the bug**
In our opinion a warning like "**[POP-107] No resource limits defined**" is wrong, if _requests.cpu_ is set.

**To Reproduce**
Define a POD with containerlimits, like (ip-masq-agent on GKE):
`  
   ...
    imagePullPolicy: IfNotPresent
    name: ip-masq-agent
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
    securityContext:...`

**Expected behavior**
This warning should only be given, if no "limits and no requests" are set.

Reason: in many situations you don't want to set "limits.cpu", because you want a container can take all cpu-resources under the respect of "reguests.cpu" of other PODS/Containers.

From another point of view: Why restrict a container to "limits.cpu", when there are enough unused cpu power left?

**Versions (please complete the following information):**
 - Popeye 0.10.1

**see also**

- https://github.com/kubernetes/design-proposals-archive/blob/8da1442ea29adccea40693357d04727127e045ed/node/resource-qos.md#compressible-resource-guaranteess
- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/resource_management_guide/sec-cpu
-

**Comment by derailed** [comment]
Fixed v0.20.0
