### ISSUE TITLE
--lint level does not affect html output

### ISSUE THREAD

**Issue by AndersBennedsgaard** [derailed/popeye#235]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
`--lint` does not affect the HTML output

**To Reproduce**
1. `popeye -l error -o html`

**Expected behavior**
Only error messages are showed in the output

**Versions (please complete the following information):**
 - OS: PopOS
 - Popeye 0.10.1
 - K8s v1.21.14-gke.3000

**Comment by Abhay3008** [comment]
I see the same issue, even spinach.yml file doesn't affect if the output is html.

**Comment by derailed** [comment]
Fixed v0.20.0
