### ISSUE TITLE
Support multiple outputs at once

### ISSUE THREAD

**Issue by rbjorklin** [derailed/popeye#237]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
It seems wasteful to run Popeye several times targeting the same namespace if I want to produce both an html report and push metrics to a Prometheus pushgateway.

**Describe the solution you'd like**
Allow specifying multiple outputs.

**Describe alternatives you've considered**
Running Popeye multiple times targeting the same namespace but with a different output format each time.

**Comment by derailed** [comment]
Fixed v0.20.0
