### ISSUE TITLE
v0.3.0 crashes at start: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by swe-covis** [derailed/popeye#24]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
Running popeye by just typing "popeye" on the shell leads to the following error:
runtime error: invalid memory address or nil pointer dereference.

The logfile is empty.

**To Reproduce**
1. Open shell
2. type popeye
3. press enter

**Expected behavior**
See popeye work as desired

**Screenshots**
![image](https://user-images.githubusercontent.com/19486627/56378676-08e80b80-620e-11e9-9fa9-ed6cc0a26245.png)

![image](https://user-images.githubusercontent.com/19486627/56409921-6cf4e900-627b-11e9-87be-13c2c1c91b9f.png)

**Versions (please complete the following information):**
 - OS: macOS
 - Popeye 0.3.0
 - K8s 1.13.5 and 1.12.6

**Additional context**
... my sincere condolences! ...

**Log**
```shell
8:01AM ERR runtime error: invalid memory address or nil pointer dereference
8:01AM ERR goroutine 1 [running]:
runtime/debug.Stack(0x2e9aae0, 0x20caa03, 0x0)
	/usr/local/Cellar/go/1.12.3/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/derailed/popeye/cmd.doIt.func1()
	/Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/cmd/root.go:50 +0x15b
panic(0x1f3e620, 0x2e83250)
	/usr/local/Cellar/go/1.12.3/libexec/src/runtime/panic.go:522 +0x1b5
github.com/derailed/popeye/internal/linter.(*Secret).checkContainerRefs(0xc00043a0b0, 0xc0001270e0, 0x25, 0xc000566140, 0x1, 0x1, 0xc000616ea0)
	/Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/internal/linter/secret.go:178 +0x26a
github.com/derailed/popeye/internal/linter.(*Secret).lint(0xc00043a0b0, 0xc0004b6ba0, 0xc00039f410, 0xc0003dc480)
	/Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/internal/linter/secret.go:85 +0x2ce
github.com/derailed/popeye/internal/linter.(*Secret).Lint(0xc00043a0b0, 0x22e15e0, 0xc0000f8540, 0x20cb19c, 0x3)
	/Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/internal/linter/secret.go:51 +0xec
github.com/derailed/popeye/pkg.(*Popeye).sanitize(0xc0000f8500)
	/Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/pkg/popeye.go:140 +0x1ef
github.com/derailed/popeye/pkg.(*Popeye).Sanitize(0xc0000f8500)
	/Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/pkg/popeye.go:106 +0x2b
github.com/derailed/popeye/cmd.doIt(0x2e8d460, 0x2eb87c0, 0x0, 0x0)
	/Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/cmd/root.go:60 +0x11b
github.com/spf13/cobra.(*Command).execute(0x2e8d460, 0xc00003a1b0, 0x0, 0x0, 0x2e8d460, 0xc00003a1b0)
	/Users/fernand/go_wk/derailed/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x2e8d460, 0x0, 0x0, 0xc0003d9f88)
	/Users/fernand/go_wk/derailed/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/fernand/go_wk/derailed/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/derailed/popeye/cmd.Execute()
	/Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/cmd/root.go:37 +0x32
main.main()
	/Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/main.go:25 +0x20
```

**Comment by derailed** [comment]
@swe-covis Thank you for reporting this so quickly and for your kind thoughts!! Stupid error on my part. I don't think I know what's going on yet but at least we will now see something in the logs. My bad! Pushing 0.3.1 now.

**Comment by derailed** [comment]
@swe-covis sorry for this mess. No quiet thinking clearly... Please try out v0.3.1 and my hope is we will have something in the now logs so we can fix...

**Comment by swe-covis** [comment]
@derailed your tools effort weight much more than such tiny bugs...
Seems this is related to an empty default namespace - there are just no resources to check.
It works fine on a namespace having resources - sorry for not checking that yesterday.

Please find the log attached to the issue.

**Comment by Shinzu** [comment]
**Versions (please complete the following information):**
 - OS: OSX 10.14.4
 - Popeye: 0.3.2 (via brew)
 - K8s: 1.12.7

logs:
```
4:23PM ERR runtime error: invalid memory address or nil pointer dereference
4:23PM ERR goroutine 1 [running]:
runtime/debug.Stack(0x2e9aae0, 0x20caa03, 0x0)
        /usr/local/Cellar/go/1.12.3/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/derailed/popeye/cmd.doIt.func1()
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/cmd/root.go:50 +0x15b
panic(0x1f3e620, 0x2e83250)
        /usr/local/Cellar/go/1.12.3/libexec/src/runtime/panic.go:522 +0x1b5
github.com/derailed/popeye/internal/linter.(*ConfigMap).checkEnv(0xc00011a638, 0xc0003e3e20, 0x18, 0xc0003ce440, 0x12, 0xc000049200, 0x27, 0xc000330900, 0x1, 0x1, ...)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/internal/linter/cm.go:146 +0x1db
github.com/derailed/popeye/internal/linter.(*ConfigMap).checkContainerRefs(0xc00011a638, 0xc0003e3e20, 0x18, 0xc000443540, 0x1, 0x1, 0xc0005c0ec8)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/internal/linter/cm.go:110 +0x16b
github.com/derailed/popeye/internal/linter.(*ConfigMap).lint(0xc00011a638, 0xc0004ba990, 0xc0004ba9f0)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/internal/linter/cm.go:41 +0x233
github.com/derailed/popeye/internal/linter.(*ConfigMap).Lint(0xc00011a638, 0x22e15e0, 0xc00026f780, 0x20cac45, 0x2)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/internal/linter/cm.go:32 +0xb0
github.com/derailed/popeye/pkg.(*Popeye).sanitize(0xc00026f740)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/pkg/popeye.go:140 +0x1ef
github.com/derailed/popeye/pkg.(*Popeye).Sanitize(0xc00026f740)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/pkg/popeye.go:106 +0x2b
github.com/derailed/popeye/cmd.doIt(0x2e8d460, 0xc00029e540, 0x0, 0x2)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/cmd/root.go:60 +0x11b
github.com/spf13/cobra.(*Command).execute(0x2e8d460, 0xc0000b8010, 0x2, 0x2, 0x2e8d460, 0xc0000b8010)
        /Users/fernand/go_wk/derailed/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x2e8d460, 0x0, 0x0, 0xc0003ddf88)
        /Users/fernand/go_wk/derailed/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/fernand/go_wk/derailed/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/derailed/popeye/cmd.Execute()
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/cmd/root.go:37 +0x32
main.main()
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/main.go:25 +0x20
```

i have the same problem, calling popeye without specifying a namespace produces above error (in the log), same also for calling it with `-n kube-system`

**Comment by derailed** [comment]
@swe-covis @Shinzu. Thank you both for reporting this! I think I've found the issue and was able to repro on my clusters.

**Comment by derailed** [comment]
@swe-covis @Shinzu  I think this is fixed now. Can you please give v0.3.3 a try and lmk if we're happier? Thank you!!

**Comment by swe-covis** [comment]
@derailed just verified it works with v0.3.3 - thanks a lot :-)

**Comment by derailed** [comment]
@swe-covis Excellent!! Thank you so much for reporting back!

**Comment by Shinzu** [comment]
@derailed works also for me on OSX(via brew) and self build on linux

**Comment by derailed** [comment]
@Shinzu Thank you for reporting back Markus! Good to hear.

**Comment by toddexp** [comment]
@derailed 

I was working with popeye today and all of a sudden it started returning this error mentioned above.

I followed the instructions on the readme:
git clone https://github.com/derailed/popeye ;# clone outside of GOPATH
cd popeye
go install ;# build and install
popeye     ;# run

This was working as recently as about an hour ago, but as of about 30 minutes ago this stopped working and started returning that runtime error above. I noticed a commit about 30 minutes ago I wonder if they are related?

**Comment by derailed** [comment]
@toddexp Thank you for reporting this. Great catch!!
 I am guessing you are running your cluster without a metrics-server?
 If so, I've noticed this issue this am and will fix on the next push.

**Comment by toddexp** [comment]
@derailed 
No problem.

It turns out that I do not have a metrics-server running in my cluster.

For now, I have reverted back to 0.3.4 and this version is working for me.

**Comment by derailed** [comment]
@toddexp Thank you for reporting back. Working on this now will push an update in a bit. Sorry for the disruption!

**Comment by derailed** [comment]
@toddexp Thank you! I think 0.3.6 should fix the npe issue. Please lmk if things are better with this drop...

**Comment by toddexp** [comment]
@derailed 

This fixed it. I appreciate the quick turnaround, thank you.
