### ISSUE TITLE
Scan all namepsaces

### ISSUE THREAD

**Issue by Shinzu** [derailed/popeye#25]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
with the `-n` flag you can choose the namespaces you like to scan, if omitted the one you set in the context is used or default(?)

**Describe the solution you'd like**
adding `all` to the flag scans all namespaces

**Describe alternatives you've considered**
maybe an `all: true` under namespaces in the spinach config file

**Comment by derailed** [comment]
@Shinzu Thank you for the report! Right, if you don't specify a namespace the default is all namespaces unless you've explicitly set a namespace in your kubeconfig in which case that namespace would be used. I think it would be a better to use a cli arg vs putting it in the config to keep the familiarity with kubectl??

**Comment by Shinzu** [comment]
👍 for a cli arg

**Comment by derailed** [comment]
@Shinzu Fixed 0.3.4! Added CLI flag --all-namespaces

**Comment by Shinzu** [comment]
@derailed thank you,  looks good

**Comment by derailed** [comment]
@Shinzu Thank you so much for reporting back! Happy to hear it working ;)
