### ISSUE TITLE
Multi-platform docker image

### ISSUE THREAD

**Issue by matheusfm** [derailed/popeye#253]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**

Unable to run popeye docker image on ARM cluster nodes.

**Describe the solution you'd like**

I'd like to run popeye docker image on ARM instances, like raspberries computers or [AWS graviton instances](https://aws.amazon.com/pt/ec2/graviton/)

**Describe alternatives you've considered**

Build multi-platform docker image
- https://docs.docker.com/build/building/multi-platform/
- https://docs.docker.com/build/ci/github-actions/multi-platform/

**Comment by kanya-approve** [comment]
When will popeye images on docker hub be updated with arm?

@derailed
