### ISSUE TITLE
Set severity levels for output 

### ISSUE THREAD

**Issue by drzero42** [derailed/popeye#257]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
It would be great to be able to get a short report with only findings of a certain severity (and higher), ie. show only errors or warnings+errors. This makes it simpler when you have a working cycle of running Popeye, fixing a warning or error and running it again to verify that the warning or error went away. Right now this cycle requires a lot of scrolling and mentally ignoring OKs, for even small-to-medium sized clusters.

**Describe the solution you'd like**
A command line argument like --min-severity=warn that would not output OKs and Infos, but only Warnings and Errors.

**Comment by derailed** [comment]
@drzero42 Did you try: `popeye -l warn` ?
