### ISSUE TITLE
additional/fine grained prometheus metrics

### ISSUE THREAD

**Issue by JCL38-ORANGE** [derailed/popeye#265]
**Is your feature request related to a problem? Please describe.**
the popeye output to prometheus brings value to the popeye tool

**Describe the solution you'd like**
do you plan to export more metrics in the next releases and which ?
metrics useful for us : 
- metrics by CR/sanitizer (scanned, faulty, ...) 
- metrics by POPX

**Comment by derailed** [comment]
Fixed v0.20.0
