### ISSUE TITLE
Container Image v0.11.2 is missing on https://hub.docker.com/r/derailed/popeye/tags

### ISSUE THREAD

**Issue by shurkanTwo** [derailed/popeye#276]
The container Image for version v0.11.2 is missing on docker.com, see: https://hub.docker.com/r/derailed/popeye/tags

**Comment by derailed** [comment]
@shurkanTwo Thank you for the heads up! It should be available now (https://hub.docker.com/layers/derailed/popeye/v0.11.2/images/sha256-8e0e53d79394e371dab07a7142b7edc8359a50f51ac0cce4ee8739cd2a0ea0f6?context=repo)
