### ISSUE TITLE
popeye 0.20.2 not showing any errors on cluster with known issues

### ISSUE THREAD

**Issue by aschleifer** [derailed/popeye#283]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
Running popeye version 0.20.2 on a cluster with known issues doesn't show any issues.

**To Reproduce**
Use popeye version 0.20.2 against a cluster with known issues. You will see it shows no errors.

**Expected behavior**
It should show the issues it has.

**Screenshots**
On the left side you see the popeye summary from version 0.20.2 and on the right side you see the summary with popey version 0.11.3. In both cases the command executed was just `popeye` without any parameters against the same cluster (taken from the kube context):

![image](https://github.com/derailed/popeye/assets/4940026/1134af03-c12a-40de-9ce3-b9be8e34ec65)

**Versions (please complete the following information):**
 - OS: Arch Linux
 - Popeye: 0.20.2
 - K8s:
```
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.5-eks-5e0fdde
```

**Comment by aschleifer** [comment]
For further information this is the log output of the run with 0.20.2:

```
11:25AM DBG Connecting to API Server [redacted]
11:25AM DBG Loading raw config from flags...
11:25AM DBG Lint 2.791633548s
11:25AM DBG Score [100]
```

**Comment by derailed** [comment]
@aschleifer Thanks for the heads up Andreas!
Could you add more details on the actual deltas in the scans between the 2 revs? 
v0.20.0 is a bit `less picky` when it comes to std k8s res. Not sure this accounts for the score deltas, but it would be good to understand which linters are either faulting or failing to report.

**Comment by aschleifer** [comment]
Hi @derailed on version 0.11.3 I get multiple issues of these error codes (executed command: `./execs/popeye | awk -d'[' '/POP-/{print $2}' | sort -u`): 

```
[POP-105]
[POP-108]
[POP-1101]
[POP-1102]
[POP-1103]
[POP-1107]
[POP-206]
[POP-400]
[POP-401]
[POP-402]
[POP-708]
[POP-1100]
[POP-1105]
[POP-304]
[POP-101]
[POP-102]
[POP-103]
[POP-104]
[POP-106]
[POP-107]
[POP-1109]
[POP-205]
[POP-208]
[POP-300]
[POP-301]
[POP-302]
[POP-303]
[POP-306]
```

**Comment by derailed** [comment]
@aschleifer Thank you for the details! I think the pb here is the starting namespace v.0.11.x uses all ns by default. v0.20.x used the context namespace is set or default. 
There should also be deltas in the res # scanned. 
Can you try `popeye -A` and see if we're happier with the deltas?

**Comment by aschleifer** [comment]
> @aschleifer Thank you for the details! I think the pb here is the starting namespace v.0.11.x uses all ns by default. v0.20.x used the context namespace is set or default. There should also be deltas in the res # scanned. Can you try `popeye -A` and see if we're happier with the deltas?

Thats it. with `-A` it works as expected again. Did I miss this change on the `v0.20.0` release notes?

**Comment by derailed** [comment]
@aschleifer Thank you for circling back Andreas!
[docs](https://github.com/derailed/popeye?tab=readme-ov-file#the-command-line)
