### ISSUE TITLE
 The k8s manifests use a version of popeye, which is not found in dockerhub.

### ISSUE THREAD

**Issue by qw1mb0** [derailed/popeye#29]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
If you try to install popeye in this way https://github.com/derailed/popeye#popeye-in-cluster, then there will be an image pull error:
```
Failed to pull image "derailed/popeye:v0.3.3": rpc error: code = Unknown desc = Error response from daemon: manifest for derailed/popeye:v0.3.3 not found
```

**To Reproduce**
1. `git clone repo`
2. Run: `kubectl apply -f k8s/popeye/ns.yml && kubectl apply -f k8s/popeye`

**Expected behavior**
In dockerhub you need to set up an image build by tags. And do not forget to fix the version of the image in the manifest

**Comment by derailed** [comment]
@qw1mb0 Thank you for this report! Doh! Looks like dockerhub is no longer building my tags ;( 
I've switched over to another repo, please see the README updates.
