### ISSUE TITLE
Integration with kube-score

### ISSUE THREAD

**Issue by faheem-cliqz** [derailed/popeye#3]
Again a nice initiative. Thank you for the effort :)

How is this different from kube-score. They both seem to do some kind of static analysis on k8s configurations.
https://github.com/zegl/kube-score

It would be nice to integrate both and have a nice experience from k9s.

I guess this will finally lead to a rules based engine something like OPA. Which has some more active elements like admission control rather than just recommendations.

**Comment by derailed** [comment]
@faheem-cliqz Thank you for sharing this comment and your thoughts! KubeScore is an awesome tool, I use it as part of my daily regime. I think there is no swiss army knife when it comes to K8s cluster operation. There is some overlap between the 2 tools indeed. However the aim of Popeye is to observe and report on deployed resource and not just scanning static artifacts. In that sense I think of Popeye as more of a CRD when comparing Helm vs CRDs or perhaps a code coverage tool vs a compiler. The fact that a pv and pvc pass the static checks is a far throw from the pvc and pv bounding at runtime. So in my mind,  Popeye is all about observing and interacting with deployed artifacts in the wild vs examining what's sitting on disk. On the other hand OPA is a gatekeeper whether a resource will be persisted in etcd or not, Popeye will sanitize once it's actually up and running in the cluster. My greatest hopes is that K8s folks will contribute to Popeye and help refine these runtime rules so everyone can benefit. I know its a bit early to see this aim but hopefully this answers your question?
