### ISSUE TITLE
Helm revision configmaps which are unused always

### ISSUE THREAD

**Issue by mitchellmaler** [derailed/popeye#30]
Right now the config maps all score on unused config maps that are the ones created by helm to keep track of revisions. Would be great to ignore these unused configmaps since they are managed by helm and kept for historical reasons.

**Comment by derailed** [comment]
@mitchellmaler Thank you for report this!! Right, I'll add a configmap exclude section on the next drop so you can customize the sanitizer based on your cluster env.

**Comment by derailed** [comment]
@mitchellmaler This should be resolved in 0.3.7. Added a new excludes section. Please see README + release notes.
