### ISSUE TITLE
deps: older version and syntax usage of `github.com/prometheus/common` blocks patching `cosign` CVE

### ISSUE THREAD

**Issue by lucasrod16** [derailed/popeye#306]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
Not sure I would classify this as a bug or feature, but it's related to an older dependency version that is affecting us from patching a CVE in our codebase.

Usage of `expfmt.FmtText` from an older version of the `github.com/prometheus/common` dependency. The `FmtText` constant has been made private since `v0.48.0`.

https://github.com/prometheus/common/blob/c1b9b7252566d10e2ef16a827f454810c7f7fa56/expfmt/expfmt.go#L24-L53
https://github.com/prometheus/common/releases/tag/v0.48.0
https://github.com/prometheus/common/pull/576

**To Reproduce**
1. Clone the [zarf](https://github.com/defenseunicorns/zarf) repository
1. Checkout the `renovate/go-github.com/sigstore/cosign/v2-vulnerability` branch from [this PR that patches a cosign vulnerability](https://github.com/defenseunicorns/zarf/pull/2437)
1. From the root of the repo, run `make` to build the zarf binary

You can also view the error here in our CI without cloning the repo and manually reproducing:

https://github.com/defenseunicorns/zarf/actions/runs/8696598566/job/23850223859?pr=2437#step:4:91

**Expected behavior**
Our build succeeds

**Screenshots**
<img width="1544" alt="popeye" src="https://github.com/derailed/popeye/assets/87675701/a6f008de-45a2-4abf-bede-23f61ffb91fc">

**Versions (please complete the following information):**
 - OS: M1 Mac
 - Popeye: v0.11.2
 - K8s: N/A

**Comment by lucasrod16** [comment]
https://github.com/derailed/popeye/blob/d09ec25f3834d2c6a171486b9726b0a91793e3f0/pkg/popeye.go#L425

**Comment by schristoff** [comment]
Hey @derailed  - any way we could get an update on this, seems like the associated PR should fix this pretty ez :)
