### ISSUE TITLE
Filter by namespace doesn't seem to be working

### ISSUE THREAD

**Issue by dserodio** [derailed/popeye#314]
**Describe the bug**
I run `popeye -n communication-engine -o jurassic`, and Popeye shows the same results as if I run `popeye -A -o jurassic`, as confirmed by `diff`. Tthere's only a couple of lines that are in different positions and a different timestamp.

**Versions (please complete the following information):**
 - macOS 14.5
 - Popeye 0.21.3
 - K8s v1.27.12

**Comment by haiwu** [comment]
Just hit the same issue

**Comment by JanMezey** [comment]
we have the same issue

**Comment by ssurovich** [comment]
I have the same issue - is this a known bug/issue right now?

**Comment by irLinja** [comment]
This issue has been open for a while, and it's breaking our pipelines.
For now, we have to pin to v.0.11.3, but it will be great to upgrade and use new features.
@derailed

**Comment by dcarrolloreilly** [comment]
Looks like in pkg/popeye.go on about line 267 there is an issue causing this.  That line is: ctx = context.WithValue(ctx, internal.KeyNamespace, client.ClusterScope) and if you override client.ClusterScope with "namespace" where namespace is the one you want to filter, it works.  There is probably a more involved fix required here but if you feel like editing this temporarily or maybe pulling the namespace flag and inserting that, you can probably get this working until there is a fix.

**Comment by dcarrolloreilly** [comment]
I have submitted PR 319  https://github.com/derailed/popeye/pull/319 to fix this.  The issue I believe is context is being overwritten within a loop and not reset.

**Comment by jainpratik163** [comment]
facing the same issue .. when we are getting fix?
