### ISSUE TITLE
Exit code error 1 in Jenkins pipeline

### ISSUE THREAD

**Issue by arushdesp** [derailed/popeye#315]
Hi all,

Running popeye in jenkins and I have an exit code error 1. I see some red erros in the cluster but I would like to continue and use the popeye report to investigate so the ci/cd even with errors must go on.
Is there a way to suppress the exit code errors natively and use the popeye for the report?Tool is awesome for the reports

**Comment by derailed** [comment]
@arushdesp I think you can use `--force-exit-zero`

**Comment by arushdesp** [comment]
You're right, thanks a lot. 
![image](https://github.com/derailed/popeye/assets/87229378/d06144c2-6fa2-4756-ad6b-c4941cce82b7)
I saw the options but I didnt think that it was referring to the ci/cd.
