### ISSUE TITLE
Cannot upload report to GCP bucket

### ISSUE THREAD

**Issue by bzaleski578** [derailed/popeye#317]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
I have deployed containerised version of Popeye in my GKE cluster and it is working nicely.
However, I seem unable to upload reports to my Cloud Storage bucket. 

**To Reproduce**
1. This command works fine: `popeye --out html`
2. But this: `popeye --out html --s3-bucket popeye --s3-region europe-west1 --s3-endpoint gs://popeye/` does not upload the report to the bucket. It also doesn't produce any error that would allow me to figure out what is wrong.
I have tried all combinations of the s3 flags (only `--s3-bucket`, `--s3-bucket` and `--s3-region`, etc...) for the same effect.
3. I appreciate the fact that my s3 parameters are of incorrect values; in this case I would say that the bug is in documentation, as it doesn't clearly state what the values should be.

**Expected behavior**
Report is uploaded upon successful execution of the command `popeye --out html --s3-bucket popeye --s3-region europe-west1 --s3-endpoint gs://popeye/`
Or
Error message is displayed

**Versions (please complete the following information):**
 - OS: Popeye containerised - Linux depl-79846bffc5-rk2t9 5.15.107+ #1 SMP Thu Jun 15 09:51:46 UTC 2023 x86_64 Linux
 - Popeye: v0.21.3
 - K8s: 1.27.13-gke.1070002

**Comment by bzaleski578** [comment]
Sorry, copy-paste went wrong. Let me state the versions again:

OS: Popeye containerised - Linux depl-79846bffc5-rk2t9 5.15.107+ #1 SMP Thu Jun 15 09:51:46 UTC 2023 x86_64 Linux
Popeye: v0.21.3
K8s: 1.27.13-gke.1070002

**Comment by derailed** [comment]
@bzaleski578 Can you share popeye's logs?

**Comment by bzaleski578** [comment]
Actually, no; I do not have that deployment any more.

I have worked this problem around by building my own Docker image based on `derailed/popeye`. My custom image contains `gcloud` and the relevant Service Account's access keys; instead of using the builtin Popeye's upload functionality, I am using `gcloud store cp`
