### ISSUE TITLE
Info: Image pull secret might not be used

### ISSUE THREAD

**Issue by swe-covis** [derailed/popeye#32]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
Having secrets being used as imagePullSecret only causes info of "secret might not be in use".

**To Reproduce**
1. Create a secret referenced only as imagePullSecret
2. run popeye
3. Check section "Secrets", it will be marked with "Used?" (Info)

**Expected behavior**
Popeye detects that the secret is in use as imagePullSecret

**Screenshots**

**Versions (please complete the following information):**
 - OS: macOS
 - Popeye 0.3.6
 - K8s 1.12.6

**Additional context**

**Comment by derailed** [comment]
@swe-covis Great catch!! I think this is now resolved in 0.3.7. Thank you for reporting this!
