### ISSUE TITLE
Popeye uses wrong field (limits instead of requests) in resource utilisation checking

### ISSUE THREAD

**Issue by d47zm3** [derailed/popeye#33]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
Popeye uses limits instead of requests to compare actual usage to stated usage, so it results in warnings about over-utilisation i.e.

kubectl reports requests/limits
```
kubectl get statefulsets.apps mongodb-primary -o json  | jq '.spec.template.spec.containers[].resources.requests'
{
  "cpu": "10m",
  "memory": "128Mi"
}

kubectl get statefulsets.apps mongodb-primary -o json  | jq '.spec.template.spec.containers[].resources.limits'
{
  "cpu": "600m",
  "memory": "612Mi"
}
```
and Popeye stated actual requests are 
```
default/mongodb-primary........................................................................😱
    😱 CPU over allocated. Requested:600m - Current:14m (4286%).
    😱 Memory over allocated. Requested:612Mi - Current:149Mi (411%).
```

**To Reproduce**
1. Comapre Popeye report and kubectl report

**Expected behavior**
Popeye doesn't report warning and uses correct fields
**Screenshots**

**Versions (please complete the following information):**
 - OS: OSX
 - Popeye 0.3.6
 - K8s Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.17"

**Additional context**

**Comment by derailed** [comment]
@d47zm3 Great catch. Thank you for the report!! Fixed v0.3.8

**Comment by swe-covis** [comment]
@derailed @d47zm3 think the checks have to consider both.
The latest version shows errors if the current usage is equal or higher than the requested.
What do you think about the following:

warning of under-/overallocation:
refers to cpu/mem requests

error regarding thresholds:
refers to cpu/mem limits

Current example of reuests mem of 3Mi but limit set to e.g. 128Mi:
![image](https://user-images.githubusercontent.com/19486627/58745410-030e5880-8451-11e9-9c20-c4e39c7ece57.png)

**Comment by derailed** [comment]
Good point. Thank you @swe-covis! I will correct this on the next drop.
