### ISSUE TITLE
dpkg: error processing archive popeye_linux_amd64.deb (--install):  trying to overwrite '/usr/share/doc/nfpm/copyright', which is also in package k9s 0.32.5

### ISSUE THREAD

**Issue by christiangierschner** [derailed/popeye#336]
Hi @derailed,
thank you for your awesome work. We really love k9s for develop kubernetes infrastructure and deployments.
Yesterday i stumbled over popeye and wanted to give it a try...
When installing the deb it gave an error:
```
/o/kubernetes-deploy [1]> sudo dpkg -i popeye_linux_amd64.deb
(Reading database ... 110180 files and directories currently installed.)
Preparing to unpack popeye_linux_amd64.deb ...
Unpacking popeye (0.21.5) ...
dpkg: error processing archive popeye_linux_amd64.deb (--install):
 trying to overwrite '/usr/share/doc/nfpm/copyright', which is also in package k9s 0.32.5
Errors were encountered while processing:
 popeye_linux_amd64.deb
 ```
This error made the connection to k9s. I can install it with --force overwrite but i think it would be better if the two apps do not interfere...

Thanks in Advance.

Greetings
Christian

**Comment by derailed** [comment]
Fixed in #359
