### ISSUE TITLE
Output logs in stdout instead of file

### ISSUE THREAD

**Issue by jchanam** [derailed/popeye#337]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
When running as a cronjob in a kubernetes cluster, there's no way to see if the execution was successful or not as there's no output, and the log file is lost.

**Describe the solution you'd like**
A new flag to be added, such as `--log-stdout` that enables this feature. I've assumed that this would only be possible if the `--save` option is used, so the outputs don't collide with each other.

**Describe alternatives you've considered**
Add a fluentd to as a sidecar to tail the file and send the logs, but I think it's a little bit overkill.

**Comment by derailed** [comment]
Added `--log none` cli args to use console logging vs file. Fixed v0.21.6
