### ISSUE TITLE
Work with less permissions (namespace only)

### ISSUE THREAD

**Issue by wodansax** [derailed/popeye#34]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
When having restricted access to the cluster, **popeye** doesn't seem to work.
If you only have access to resources in a namespace you will get messages like:
```
message: 'configmaps is forbidden: User "system:serviceaccount:xxx:xxx"
          cannot list resource "configmaps" in API group "" at the cluster scope'
```
although a request like this works (same kubeconfig):
`kubectl get pvc -n "namespace"`

**Describe the solution you'd like**
Maybe i'm using popeye wrong or it is not supported atm?

**Describe alternatives you've considered**
As we are consumers of namespace we don't have access to serviceaccounts with more permissions on cluster level.

**Additional context**
These are the permissions we are missing due to restricted access:

```
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:     ["get", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources:
  - pods
  - nodes
  verbs:     ["get", "list"]
```

**Comment by derailed** [comment]
@wodansax Fixed in v0.3.10!
