### ISSUE TITLE
Add Cillium support to POD-1204/1205

### ISSUE THREAD

**Issue by Plork** [derailed/popeye#342]
**Describe the bug**
At the moment is seems that  [checkNPs](https://github.com/derailed/popeye/blob/master/internal/lint/pod.go#L101) only checks for Network Policies and not for Cilium.

**Expected behavior**
I would expect that when Cilium is detected.  The ingress and egress are checked for a CNP and not a network policy.

**Versions (please complete the following information):**
 - Popeye [0.21.5]
 - K8s [1.28]

**Comment by derailed** [comment]
@Plork Popeye does support Cilium resources when available. 
There should be separate sections in the report for cnp and ccnp.
