### ISSUE TITLE
xUnit compatible output

### ISSUE THREAD

**Issue by nvtkaszpir** [derailed/popeye#35]
**Is your feature request related to a problem? Please describe.**
Would be nice if popeye had xUnit (JUnit XML) compatible output.

This is quite common format for Jenkins artifacts.
https://jenkins.io/blog/2016/10/31/xunit-reporting/
https://llg.cubic.org/docs/junit/

**Describe the solution you'd like**
Running 
```bash
popeye -o junit-xml
```
would produce XML output.

**Describe alternatives you've considered**
Json or YAML, already exists, but would require additional parsing with other tools.

**Additional context**
This would generally improve popeye integration with some CI/CD tools, where jurassic output is too ancient while default output is to fancy :)

**Comment by derailed** [comment]
@nvtkaszpir Thank for this report. I love your additional context section! I'll take a look and see how we would output in xml. Any specifics you would be looking for here?

**Comment by nvtkaszpir** [comment]
No specifics.

Another idea would be just to produce output in such way that other tools can easily parse it, for example using https://github.com/tebeka/go2xunit

**Comment by derailed** [comment]
@nvtkaszpir Thank you for the pointers! I'll take a look...

**Comment by derailed** [comment]
@nvtkaszpir Thank you for the info on this. In  v0.4.1(see v0.4.0 release notes) we've added a -o junit output. This might still need a bit of tuning but it's a start in formatting the sanitizer output using a junit schema. Please feel free to open new issues if you need a more customized output. We can iterate here as I think it will be useful for lots of folks. Thank you for this issue and let me know if we're happier...
