### ISSUE TITLE
Allow foreground execution, with output to STDOUT/STDERR and disabling output to popeye.log file

### ISSUE THREAD

**Issue by frjaraur** [derailed/popeye#356]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
Not sure if there is really a problem. Execution of the following line creates annoying DBG messages in /tmp/popeye.log:
```
POPEYE_REPORT_DIR=/tmp popeye -A -o html --save --output-file index.html --force-exit-zero -f  myspinachs.yaml
```
I really need the report but there's no option for disabling debugging output or even redirect the popeye log somewhere. Scripting makes it possible but this shouldn't be the only option. I am not sure if I am missing an environment variable or optional argument, but I have read the docs and code to try to find it.

It would be nice to be able to have a fully foreground command line eliminating popeye.log output for Kubernetes execution. Maybe I'm doing something wrong but I always get debugging messages on popeye.log and there isn't any way of avoiding them (or at least I haven't found it). Why do I get DBG messages???

**Describe the solution you'd like**
It will be easy to add a foreground option to always expose errors and/or debugging information directly into the standard or error ouputs.

**Describe alternatives you've considered**
Well it's not problematic to add some pre-execution cleaning the old popeye.log file but it is not elegant and it is not included out-of-box at command-line, a simple script will be required....

Thanks in advance for the consideration and please let me know if I can help to develop or change the code to make it happens.
Javier R.

**Comment by derailed** [comment]
Added cli arg `--logs none` to use stdout logging vs file in v0.21.6
