### ISSUE TITLE
Describe how output can be used when popeye runs on k8s

### ISSUE THREAD

**Issue by Siegfriedk** [derailed/popeye#36]
Hi,

we playing around with popeye and i like how it works. Following the k8s guide, i'm assuiming that i will receive the output of the job manually.

Could it be added to the README.md?

Tx,

Sigi

**Comment by derailed** [comment]
@Siegfriedk Thank you for the report! At this time Popeye supports yaml or json outputs. You could define an output to parse the sanitizer report and scan and report on scores. We will offer more formats as Popeye solidifies in the future. Specifically what kind of report are you looking to extract out?
