### ISSUE TITLE
Configmaps and Secrets in a projected volume not detected as used

### ISSUE THREAD

**Issue by tylergmuir** [derailed/popeye#365]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
Projected volumes are not checked for config maps and secrets so they get reported as potentially unused.

**To Reproduce**
1. Have a pod/deployment with a projected volume that is comprised of multiple items (configmaps and/or secrets)
2. Run popeye

**Expected behavior**
Since the configmaps/secrets are mapped to the pod/deployment via the projected volume, I would expect they get reported as used.

**Versions (please complete the following information):**
 - OS: OSX
 - Popeye 0.21.5
 - K8s 1.27.11

**Comment by bpfoster** [comment]
Am seeing the same behavior.
