### ISSUE TITLE
Boom! runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ashishxooa** [derailed/popeye#37]
Hi, 

Great tool, looks very promising. Unfortunately not working for me. Not sure if I am doing anything wrong or it's a bug. The spinach file is the same one you have shared as a sample. 

I am using Osx and popeye version is 0.3.10.

➜  popeye popeye -f spinach.yaml
 ___     ___ _____   _____                       S          .-'-.
| _ \___| _ \ __\ \ / / __|                       o     __| K    `\
|  _/ _ \  _/ _| \ V /| _|                         S   `-,-`--._   `\
|_| \___/_| |___| |_| |___|                       []  .->'  O     `|-'
  Biffs`em and Buffs`em!                            `=/ (__/_       /
                                                      \_,    `    _)
                                                         `----;  |

Boom! runtime error: invalid memory address or nil pointer dereference
➜  popeye
➜  popeye
➜  popeye popeye --context k8s-cluster.ci.xooa.io
 ___     ___ _____   _____                       S          .-'-.
| _ \___| _ \ __\ \ / / __|                       o     __| K    `\
|  _/ _ \  _/ _| \ V /| _|                         S   `-,-`--._   `\
|_| \___/_| |___| |_| |___|                       []  .->'  O     `|-'
  Biffs`em and Buffs`em!                            `=/ (__/_       /
                                                      \_,    `    _)
                                                         `----;  |
Boom! runtime error: invalid memory address or nil pointer dereference

**Comment by derailed** [comment]
@ashishxooa Thanks for the report! Is there anything in the popeye log file that might shade some light on this issue?

**Comment by ashishxooa** [comment]
@derailed this is what I can see. 

> [[90m4:03PM^[[0m ^[[1m^[[31mERR^[[0m^[[0m runtime error: invalid memory address or nil pointer dereference
^[[90m4:03PM^[[0m ^[[1m^[[31mERR^[[0m^[[0m goroutine 1 [running]:
runtime/debug.Stack(0x2e7bfa0, 0x20c0d03, 0x0)
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/derailed/popeye/cmd.doIt.func1()
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/cmd/root.go:52 +0x196
panic(0x1f32c20, 0x2e64850)
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5
github.com/derailed/popeye/internal/sanitize.(*PodDisruptionBudget).checkInUse(0xc0004d7b58, 0xc000358de0, 0x23, 0xc0001b0420)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/internal/sanitize/pdb.go:50 +0x6a
github.com/derailed/popeye/internal/sanitize.(*PodDisruptionBudget).Sanitize(0xc0004d7b58, 0x22d0640, 0xc0002354c0, 0xc0003baff0, 0xc0003bafe8)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/internal/sanitize/pdb.go:37 +0xbd
github.com/derailed/popeye/internal/scrub.(*PodDisruptionBudget).Sanitize(0xc0003bafe0, 0x22d0640, 0xc0002354c0, 0x20c141e, 0x3)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/internal/scrub/pdb.go:40 +0x6f
github.com/derailed/popeye/pkg.(*Popeye).sanitize(0xc000235440)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/pkg/popeye.go:135 +0x670
github.com/derailed/popeye/pkg.(*Popeye).Sanitize(0xc000235440)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/pkg/popeye.go:99 +0x2b
github.com/derailed/popeye/cmd.doIt(0x2e6e8e0, 0xc0001eb0c0, 0x0, 0x2)
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/cmd/root.go:62 +0x11b
github.com/spf13/cobra.(*Command).execute(0x2e6e8e0, 0xc00003a1c0, 0x2, 0x2, 0x2e6e8e0, 0xc00003a1c0)
        /Users/fernand/go_wk/derailed/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x2e6e8e0, 0x0, 0x0, 0xc0003b9f88)
        /Users/fernand/go_wk/derailed/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/fernand/go_wk/derailed/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/derailed/popeye/cmd.Execute()
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/cmd/root.go:38 +0x32
main.main()
        /Users/fernand/go_wk/derailed/src/github.com/derailed/popeye/main.go:29 +0x20

**Comment by derailed** [comment]
@ashishxooa Tx! Fixed v0.3.11!

**Comment by ashishxooa** [comment]
That was really quick, it works now. Keep up the good work.

Cheers.
