### ISSUE TITLE
Disable over allocation

### ISSUE THREAD

**Issue by jclarksnps** [derailed/popeye#39]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
The problem is that the over-allocation check is incredibly subjective, since it seems to just grab the current metric for each service.  If you want to sanity test a cluster that may have absolutely no load on it, you will always get piles of warnings that are for the most part meaningless.  In a sanity test of a cluster's configuration, in some cases you only care about under-allocated as your request/limits are set for real production values.

**Describe the solution you'd like**
A way to disable the over-allocation test, tried playing with the values and couldn't get it to just go away.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by derailed** [comment]
@jclarksnps Thank you for this report! I agree over-allocation warnings yields false positive when the cluster is not under heavy load. I will add an option to silence these in the next drop.

**Comment by whites11** [comment]
I just came by to post exactly the same thought, so +1 here.

**Comment by derailed** [comment]
@jclarksnps @whites11 Fixed v0.3.13!

**Comment by whites11** [comment]
Thanks!
