### ISSUE TITLE
popeye via Docker - Set endpoint apiserver

### ISSUE THREAD

**Issue by rafaelsilvaa10** [derailed/popeye#41]
Hello,

How to set my api endpoint on docker popeye?

I am using 
`docker build .`

`Sending build context to Docker daemon  4.068MB
Step 1/11 : FROM golang:1.12.3-alpine AS build
 ---> 821acdc20eb8
Step 2/11 : ENV VERSION=v0.3.0 GO111MODULE=on PACKAGE=github.com/derailed/popeye
 ---> Using cache
 ---> 0a401431d7d7
Step 3/11 : WORKDIR /go/src/$PACKAGE
 ---> Using cache
 ---> 965320b59c77
Step 4/11 : COPY go.mod go.sum main.go ./
 ---> Using cache
 ---> 2d628072a157
Step 5/11 : COPY internal internal
 ---> Using cache
 ---> cd745293c32c
Step 6/11 : COPY pkg pkg
 ---> Using cache
 ---> e885f8bddbb9
Step 7/11 : COPY cmd cmd
 ---> Using cache
 ---> bba94286a838
Step 8/11 : RUN apk --no-cache add git ;  CGO_ENABLED=0 GOOS=linux go build -o /go/bin/popeye   -ldflags="-w -s -X $PACKAGE/cmd.version=$VERSION" *.go
 ---> Using cache
 ---> 7860fc5c32a9
Step 9/11 : FROM alpine:3.9.3
 ---> cdf98d1859c1
Step 10/11 : COPY --from=build /go/bin/popeye /bin/popeye
 ---> Using cache
 ---> 73aa47a20000
Step 11/11 : ENTRYPOINT [ "/bin/popeye" ]
 ---> Using cache
 ---> 00da1ca5cf57
Successfully built 00da1ca5cf57`

after that, i start my docker using:

`docker run 00da1ca5cf57`

I receiving:
`
PERSISTENTVOLUMES (2 SCANNED)                                                  💥 2 😱 0 🔊 0 ✅ 0 0٪
┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅
  · pods...........................................................................................💥
    💥 Get http://localhost:8080/api/v1/pods: dial tcp 127.0.0.1:8080: connect: connection refused.
  · services.......................................................................................💥
    💥  Get http://localhost:8080/api/v1/persistentvolumes: dial tcp 127.0.0.1:8080: connect:
        connection refused.
`

How to i set my .kube/config to use in my docker popeye?

**Comment by derailed** [comment]
@rafaelsilvaa10 You should be able to pass in args such as --kubeconfig=mykubeconfigpath as parameter on your container.

**Comment by rafaelsilvaa10** [comment]
thanks for reply.
I need to mount kubeconfig path such as volume in my container popeye?

**Comment by rafaelsilvaa10** [comment]
thanks for reply @derailed 
I need to mount kubeconfig path such as volume in my container popeye?

**Comment by rafaelsilvaa10** [comment]
thanks, its work.
