### ISSUE TITLE
Consider pods running with "default" service account a warning or error

### ISSUE THREAD

**Issue by naseemkullah** [derailed/popeye#42]
Would it fall under popeye's scope to check for best practices such as this?

**Comment by derailed** [comment]
@naseemkullah Thank you for this report! Yes I think this is a valid check.

**Comment by naseemkullah** [comment]
My pleasure @derailed.
Furthermore, if interested in encompassing checks with regards to `securityContext` (whether at pod level or container level) as well, https://kubesec.io/ have some nice ideas (to check is pod is running as non-root for example).

**Comment by derailed** [comment]
@naseemkullah Thank you for the pointer! I'll take a peek and see how we can start surfacing more security best practices in Popeye.

**Comment by naseemkullah** [comment]
My pleasure @derailed , I just discovered this tool as well that covers this sort of thing: https://github.com/Shopify/kubeaudit ...could maybe get some ideas from it as well.

**Comment by derailed** [comment]
@naseemkullah Thank you for your pointers on this!! v0.4.1 now performs some basic security checks. More to come on this... Please see v0.4.0 release notes.

**Comment by naseemkullah** [comment]
Excellent!
