### ISSUE TITLE
Parametrize what is considered a warning or error by the SpinachYAML file

### ISSUE THREAD

**Issue by elvisFabian** [derailed/popeye#43]
**Is your feature request related to a problem? Please describe.**
In my scenario I would like **resource request/presence limits** to be an `error`.
In the current scenario it is a warning.

**Describe the solution you'd like**
Parametrize  what is considered a warning or error by the SpinachYAML file.
This could be used for any Sanitizers

**Comment by derailed** [comment]
@elvisFabian Excellent!! Thank you for your input. I agree with this concept as cluster owners should be able to choose the sanitizers severity levels for their clusters. I have been thinking about using a sanitizer issue classification. Much like HTTP error codes. I think we could then use your concept to further classify an issue as a info/warning/error/etc..  
For instance a Popeye-404: Warning: Missing container resources could then be overridden in a config file as an error on your cluster. What do you guys think?

**Comment by derailed** [comment]
@elvisFabian Fixed v0.4.1! Please see v0.4.0 release notes and how you can override the severity in your spinach.yml config file. Thank you!
