### ISSUE TITLE
Junit shows all tests as failed in jenkins

### ISSUE THREAD

**Issue by gabeduke** [derailed/popeye#44]
This is super exciting there is now junit support! Our Jenkins job is showing all of the tests as `failed` in the results. I don't have any output to paste right now. If you are unable to see what's going on I'll be happy to try and recreate in my private profile.

- run tests and pipe the output to a results file (the `--save` flag was storing the file in the Jenkins workspace in a location our job does not have access to.)
- use `junit <path to results file>` to chart the results

**Comment by gabeduke** [comment]
I was able to reproduce this using a junit viewing tool:

[junit viewer](https://www.npmjs.com/package/junit-viewer)

```
popeye -o junit --save
junit-viewer --results=<path/to/results> --save=results.html

# view results
xdg-open file:///$(pwd)/results.html
```

**Comment by derailed** [comment]
@gabeduke Thank you so much for this issue! I'll take a look as I think I might have hosed the junit rendering slightly. I think we should just report and fail tests in case of sanitizer warning or error.  Would this make more sense? Sorry it's been a while for me with junit and xml ;(

**Comment by gabeduke** [comment]
@derailed I took a stab at adding levels to the report builder but I could not get the tally's working yet. I'm not sure I understand why warning and error should be the same level, can you explain?

https://github.com/derailed/popeye/compare/master...gabeduke:junit

**Comment by derailed** [comment]
@gabeduke Sure - Popeye issues sanitizer issues as Info, Warning, Error. Warnings and errors count against your cluster score. There are also regular errors ie Popeye failed to run. In Junit schema, a test case can only have failure or error. So we're kind of shoe-horning the sanitizer output to fit the schema here. I'll drop a new rev v0.4.2 and see if this help some on the original issue.

**Comment by gabeduke** [comment]
That makes sense, thanks for clarifying. The new version fixes this issue and also now includes passing tests which is great :)

`diff /tmp/popeye/sanitizer_microk8s-cluster_1565052255769487845.xml /tmp/popeye/sanitizer_microk8s-cluster_1565052100772076630.xml`
```diff
> 		<testcase classname="" name="Version"></testcase>
< 		<testcase classname="" name="Version">
< 			<failure message="[POP-406] K8s version OK" type="ok"></failure>
< 		</testcase>
```

**Comment by derailed** [comment]
@gabeduke Glad to hear it's looking better now. Thank you for your response!
