### ISSUE TITLE
Add command line option to report only above a specific level

### ISSUE THREAD

**Issue by djablonski-moia** [derailed/popeye#47]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
In favour of getting a quick overview it would be nice to reduce the output to just those results above a specified level, e.g. WARN.

**Describe the solution you'd like**
If I would provide the command line option, e.g. `--min-level warn`, I would get a report which just contains the results which have a level of WARN or ERROR.

**Describe alternatives you've considered**
None.

**Additional context**
No additional context.

**Comment by derailed** [comment]
@djablonski-moia Thank you for your report. I think what your are looking for is already there.

```shell
popeye -l warn # produces a report that only contains warnings and errors
popeye help for all available flags
``

Does this make sense?

**Comment by djablonski-moia** [comment]
Absolutely! Sorry for me overlooking this option (I was just seeing "lint" and was looking for log).
