### ISSUE TITLE
Ingresses can not be found on clusters running K8s 1.13

### ISSUE THREAD

**Issue by djablonski-moia** [derailed/popeye#51]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
When running popeye against a 1.13 cluster, in which the ingresses still need to have àpiVersion: extensions/v1beta1`, it fails with the following message:

```
INGS (1 SCANNED)                                                               💥 1 😱 0 🔊 0 ✅ 0 0٪
┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅
  · ingresses......................................................................................💥
    💥 the server could not find the requested resource.
```

**To Reproduce**
1. Running a cluster with K8s 1.13, and existing ingresses, just run `popeye -s ing`
2. See error

**Expected behavior**
Ingresses are being found & sanitized.

**Versions (please complete the following information):**
 - OS: Mac OSX Mojave (10.14.6)
 - Popeye [e.g. 0.4.3]
 - K8s [e.g. 1.13.0]

**Additional context**
I was able to fix this locally by using `Ingress` from `k8s.io/api/extensions/v1beta1`instead of `k8s.io/api/networking/v1beta1`, but this breaks compatibility with newer K8s versions. I don't know how to fix this properly... ☹️

**Comment by derailed** [comment]
@djablonski-moia Thank you for this report! I'll take a look and see how Popeye can support older resources. I think I have some ideas there. That said and given the various CVEs it might be wise to run newer k8s versions (if possible!!) as the Popeye currently does not scan for those (which could be a great addition...)

**Comment by derailed** [comment]
@djablonski-moia Reverted to extensions group until networking is actually surfaced. Please see 0.6.0. Thank you!!

**Comment by calvinbui** [comment]
We use 1.13 on GKE as it's [what Google considers 'stable'](https://cloud.google.com/kubernetes-engine/docs/release-notes-stable)

Similarly I get the message to use `networking` which doesn't exist on 1.13

```
[POP-403] Deprecated Ingress API group "extensions/v1beta1". Use "networking.k8s.io/v1beta1" instead.
```
