### ISSUE TITLE
What is the meaning of the icons in the output?

### ISSUE THREAD

**Issue by slmingol** [derailed/popeye#6]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
The output shows icons with various status counts next to them. What is the meaning of these within each section of the output generated by Popeye?

**To Reproduce**
Merely run Popeye.

**Expected behavior**
The README.md or some docs should describe the various output's meaning.

**Versions (please complete the following information):**
 - OS: OSX
 - Popeye 0.1.4
 - openshift v3.11.43
 - kubernetes v1.11.0+d4cacc0

**Comment by derailed** [comment]
@slmingol Tx for the report! Agreed! I'll add more docs about this on the README.

**Comment by derailed** [comment]
@slmingol Readme updated per you recommendations. Tx!
