### ISSUE TITLE
EKS resources are considered unused

### ISSUE THREAD

**Issue by sheerun** [derailed/popeye#62]
When deploying on AWS, EKS creates some default namespaces popeye complains about them:

**Describe the bug**

```
  · kube-node-lease................................................................................🔊
    🔊 [POP-400] Used? Unable to locate resource reference.
  · kube-public....................................................................................🔊
    🔊 [POP-400] Used? Unable to locate resource reference.
```

**To Reproduce**
1. Create cluster with EKS
2. Run popeye

**Expected behavior**

Default setup on EKS has no warnings

**Comment by derailed** [comment]
@sheerun Thank you for this report! Indeed there are used internally and Popeye can't pick up the references. So you will have to exclude these using a spinach.yml file. Please see the release notes for 0.6.0 and the example spinach file in this repo. Thank you!
