### ISSUE TITLE
HTML friendly output

### ISSUE THREAD

**Issue by mycrEEpy** [derailed/popeye#73]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
We use Jenkins to run popeye and want to present the result as HTML report.

**Describe the solution you'd like**
Either a direct html output or jurassic output should use html friendly characters (see screenshot).

**Describe alternatives you've considered**
We also use Junit format and let Jenkins read that, but the normal text output is way clearer for a developer.

**Additional context**
![image](https://user-images.githubusercontent.com/6517708/72659490-a13f3680-39c0-11ea-8287-03f91be056c5.png)

**Comment by mycrEEpy** [comment]
With fix from #74 :

![image](https://user-images.githubusercontent.com/6517708/72677455-ee90d600-3a9c-11ea-8295-e510320afa2c.png)

**Comment by derailed** [comment]
@mycrEEpy Thanks to the great PR from @BarakStout. This is now a reality. v0.7.0!
