### ISSUE TITLE
allow popeye | more 

### ISSUE THREAD

**Issue by gadelkareem** [derailed/popeye#76]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

I need to use `| more` with popeye

**Comment by derailed** [comment]
@gadelkareem I think you can do it now...

```shell
popeye -o jurassic | more
popeye -n default -s pod,deploy -o jurassic | more
```

**Comment by gadelkareem** [comment]
No colors?...😞

**Comment by derailed** [comment]
popeye | more -R 😁
