### ISSUE TITLE
Flag -n seems not to work for pods

### ISSUE THREAD

**Issue by swe-covis** [derailed/popeye#8]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
Running ```popeye -n <my_namespace>``` gives results for pods in all namespaces.
Results for services are filtered correctly.

**Expected behavior**
Running ```popeye -n <my_namespace>``` should give me results only for the desired namespace.

**Versions (please complete the following information):**
 - OS: macOS
 - Popeye 0.1.4
 - K8s 1.12.6

**Additional context**
REALLY useful tool and again (-> k9s) a great job.
Thank you!

**Comment by derailed** [comment]
@swe-covis Thank you for the report! 

I've noticed that too. I have a fix in place in the next drop. Tx!!

**Comment by derailed** [comment]
@swe-covis let's try 0.2.0 and see if this helps... Tx!!
