### ISSUE TITLE
Distribute popeye via krew?

### ISSUE THREAD

**Issue by corneliusweig** [derailed/popeye#84]
:wave: Hello, maintainer of the kubectl plugin manager [krew](https://github.com/kubernetes-sigs/krew) here.

What do you think about making your plugin available via krew? You would benefit from

- Greater visibility due to krew's large user basis.
- Easier installs.
- Seamless upgrades for new plugin versions.

Krew already has around [80 plugins](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins.md) and more are coming in. Your resource analyzer looks like a cool addition to the plugin index. See our [development guide](https://github.com/GoogleContainerTools/krew/blob/master/docs/DEVELOPER_GUIDE.md) if you're interested. Please also consult our [naming guide](https://github.com/kubernetes-sigs/krew/blob/master/docs/NAMING_GUIDE.md) about the plugin name. I presume that `kubectl-popeye` would be an acceptable plugin name.

**Comment by derailed** [comment]
@corneliusweig You had me at `Hello`...

 It's on the plan but just didn't get to it yet. Thank you for your thoughts and for stopping by!

**Comment by corneliusweig** [comment]
Well that was quick!
https://github.com/kubernetes-sigs/krew-index/pull/521
