### ISSUE TITLE
Colors aren't displayed in terminal

### ISSUE THREAD

**Issue by tlereste** [derailed/popeye#88]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
When I run popeye the colors aren't displayed in terminal.

**To Reproduce**
1. Run command `popeye`
2. The colors aren't displayed in terminal

**Versions (please complete the following information):**
 - OS: [Debian]
 - Popeye  [0.7.1]
 - K8s [1.17]

**Additional context**
N/A

**Comment by derailed** [comment]
@tlereste I think your mileage varies based on your terminal of choice. Typically on unix system you'll have to set this env var:

```shell
 export TERM=xterm-256color
```
