### ISSUE TITLE
`-A` and `--all-namespaces` don't seem to work

### ISSUE THREAD

**Issue by ryuheechul** [derailed/popeye#94]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_bug.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Describe the bug**
`-A` and `--all-namespaces` is being ignored and checking  **only** current namespace.

**To Reproduce**
1. `$ popeye -A`
2. or `$ popeye -all-namespaces`
3. See `popeye` checks only current namespace.

**Expected behavior**
checking all the namespaces

**Screenshots**
(none)

**Versions (please complete the following information):**
 - OS: macOS
 - Popeye 0.8.1
 - K8s: client: 1.17.3, server: 1.15.9

**Additional context**
(none)

**Comment by ryuheechul** [comment]
and thanks for the developments of both k9s and popeye great tools 👍🏼

**Comment by derailed** [comment]
@ryuheechul Thank you for your kind words and for this issue. I'll take a look...

**Comment by peddyhh** [comment]
tnx for popeye, great work.

With Gcloud I confirm the bug:
**kubectl version**   
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.7", GitCommit:"8fca2ec50a6133511b771a11559e24191b1aa2b4", GitTreeState:"clean", BuildDate:"2019-09-18T14:47:22Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**kubectl version**                                                                                                                
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.27", GitCommit:"145f9e21a4515947d6fb10819e5a336aff1b6959", GitTreeState:"clean", BuildDate:"2020-02-21T18:01:40Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by derailed** [comment]
@peddyhh @ryuheechul  Thank you both for your kind words and for reporting this! Fixed v0.8.2
