### ISSUE TITLE
Question: Is there a list where I can look up the [POP-*] issue numbers?

### ISSUE THREAD

**Issue by mstoetzer** [derailed/popeye#95]
Are there more details about the issue numbers that appear in the report? I'm just curious. What's behind those numbers?

Thanks for this great tool :+1:

**Comment by derailed** [comment]
@mstoetzer Thank you! I'll need some TLC on the docs. In the meantime,  the currently supported codes are defined here [codes](https://github.com/derailed/popeye/blob/8ad662df7364b98445c5758e8d7beac431866517/internal/issues/codes.go#L44)

**Comment by MichaelJDrK** [comment]
popeye reports for one deployment:
[POP-502] ReplicaSet collisions detected (1).

Can you shortly explain what that means?

**Comment by derailed** [comment]
@mstoetzer This is a hash collision avoidance mechanism when a new ReplicaSet/ControllerRevision hash need to be generated. This field is usually unset or 0. I think this is a bug as this is not flagging an actual issue with either a dp, sts, or ds. I'll fix this in the next drop. Thank you for flagging this issue!

**Comment by derailed** [comment]
@mstoetzer Fixed v0.8.4!
