### ISSUE TITLE
Is it possible to use the popeye command to fail a CI/CD build if there are warning or errors exists.

### ISSUE THREAD

**Issue by prashantkalkar** [derailed/popeye#98]
<img src="https://raw.githubusercontent.com/derailed/popeye/master/assets/popeye_feature.png" align="right" width="100" height="auto"/>

<br/>
<br/>
<br/>

**Is your feature request related to a problem? Please describe.**
It will be great if popeye can report failure if it is used with the command line lint option to get details of the warning and errors. This should allow failing the build. 
I understand that this can only be a post-deployment check and before since popeye seems to work on the state of the cluster. 

**Describe the solution you'd like**
Get failure status (possibly optional flag) from the popeye command line for the report generated. 

**Describe alternatives you've considered**
I am not completely sure whether popeye is designed to be used in this fashion. If a better alternative exists to expose issues as soon as possible please let me know.

**Comment by nigel4321** [comment]
On a related note, it would be nice if we could get a return code for errors, that is the code returned on the shell should be non-zero (Normally accessible as $?).

Use case:
I would like to run "popeye -l error" in an automated job, the job should fail if the command returns non-zero

**Comment by derailed** [comment]
@prashantkalkar @nigel4321 Thank you both for the feedback! Popeye will now return a non zero exit if warnings/errors are found in the scans.
